// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package emailtemplate.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Provide a html string as input, the action will strip off all html elements and returns a plain text to 
 */
public class ConvertHTMLBodyToPlainText extends CustomJavaAction<String>
{
	private String HTMLBody;

	public ConvertHTMLBodyToPlainText(IContext context, String HTMLBody)
	{
		super(context);
		this.HTMLBody = HTMLBody;
	}

	@Override
	public String executeAction() throws Exception
	{
		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "ConvertHTMLBodyToPlainText";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
