// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package emailtemplate.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SendEmail extends CustomJavaAction<Boolean>
{
	private String SMTPHost;
	private String SMTPUserName;
	private String SMTPPassword;
	private String CCAddresses;
	private String BCCAddresses;
	private String ToAddresses;
	private String FromAddress;
	private String HtmlBody;
	private String PlainBody;
	private String Subject;
	private Long SMTPPort;
	private java.util.List<IMendixObject> __AttachmentList;
	private java.util.List<system.proxies.FileDocument> AttachmentList;
	private Boolean UseSSL;
	private Boolean UseTLS;

	public SendEmail(IContext context, String SMTPHost, String SMTPUserName, String SMTPPassword, String CCAddresses, String BCCAddresses, String ToAddresses, String FromAddress, String HtmlBody, String PlainBody, String Subject, Long SMTPPort, java.util.List<IMendixObject> AttachmentList, Boolean UseSSL, Boolean UseTLS)
	{
		super(context);
		this.SMTPHost = SMTPHost;
		this.SMTPUserName = SMTPUserName;
		this.SMTPPassword = SMTPPassword;
		this.CCAddresses = CCAddresses;
		this.BCCAddresses = BCCAddresses;
		this.ToAddresses = ToAddresses;
		this.FromAddress = FromAddress;
		this.HtmlBody = HtmlBody;
		this.PlainBody = PlainBody;
		this.Subject = Subject;
		this.SMTPPort = SMTPPort;
		this.__AttachmentList = AttachmentList;
		this.UseSSL = UseSSL;
		this.UseTLS = UseTLS;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		this.AttachmentList = new java.util.ArrayList<system.proxies.FileDocument>();
		if (__AttachmentList != null)
			for (IMendixObject __AttachmentListElement : __AttachmentList)
				this.AttachmentList.add(system.proxies.FileDocument.initialize(getContext(), __AttachmentListElement));

		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "SendEmail";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
