// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package testsuite.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class Long1000 extends CustomJavaAction<java.lang.Long>
{
	private java.lang.Long longVar;

	public Long1000(IContext context, java.lang.Long longVar)
	{
		super(context);
		this.longVar = longVar;
	}

	@Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		String longStr = longVar.toString();
		if(longStr.length() > 10){
			longStr = "0";
		} else {
			longStr = (longVar.toString());
			longStr += "000";
		}

		return Long.parseLong(longStr);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "Long1000";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
