// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxmodelreflection.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class Microflows
{
	private final IMendixObject microflowsMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "MxModelReflection.Microflows";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Module("Module"),
		CompleteName("CompleteName"),
		Microflows_InputParameter("MxModelReflection.Microflows_InputParameter"),
		Microflows_Output_Type("MxModelReflection.Microflows_Output_Type"),
		Microflows_Module("MxModelReflection.Microflows_Module");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public Microflows(IContext context)
	{
		this(context, Core.instantiate(context, "MxModelReflection.Microflows"));
	}

	protected Microflows(IContext context, IMendixObject microflowsMendixObject)
	{
		if (microflowsMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("MxModelReflection.Microflows", microflowsMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a MxModelReflection.Microflows");

		this.microflowsMendixObject = microflowsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Microflows.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static mxmodelreflection.proxies.Microflows initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return mxmodelreflection.proxies.Microflows.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static mxmodelreflection.proxies.Microflows initialize(IContext context, IMendixObject mendixObject)
	{
		return new mxmodelreflection.proxies.Microflows(context, mendixObject);
	}

	public static mxmodelreflection.proxies.Microflows load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return mxmodelreflection.proxies.Microflows.initialize(context, mendixObject);
	}

	public static java.util.List<mxmodelreflection.proxies.Microflows> load(IContext context, String xpathConstraint) throws CoreException
	{
		java.util.List<mxmodelreflection.proxies.Microflows> result = new java.util.ArrayList<mxmodelreflection.proxies.Microflows>();
		for (IMendixObject obj : Core.retrieveXPathQuery(context, "//MxModelReflection.Microflows" + xpathConstraint))
			result.add(mxmodelreflection.proxies.Microflows.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final String getName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(IContext context, String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Module
	 */
	public final String getModule()
	{
		return getModule(getContext());
	}

	/**
	 * @param context
	 * @return value of Module
	 */
	public final String getModule(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Module.toString());
	}

	/**
	 * Set value of Module
	 * @param module
	 */
	public final void setModule(String module)
	{
		setModule(getContext(), module);
	}

	/**
	 * Set value of Module
	 * @param context
	 * @param module
	 */
	public final void setModule(IContext context, String module)
	{
		getMendixObject().setValue(context, MemberNames.Module.toString(), module);
	}

	/**
	 * @return value of CompleteName
	 */
	public final String getCompleteName()
	{
		return getCompleteName(getContext());
	}

	/**
	 * @param context
	 * @return value of CompleteName
	 */
	public final String getCompleteName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.CompleteName.toString());
	}

	/**
	 * Set value of CompleteName
	 * @param completename
	 */
	public final void setCompleteName(String completename)
	{
		setCompleteName(getContext(), completename);
	}

	/**
	 * Set value of CompleteName
	 * @param context
	 * @param completename
	 */
	public final void setCompleteName(IContext context, String completename)
	{
		getMendixObject().setValue(context, MemberNames.CompleteName.toString(), completename);
	}

	/**
	 * @return value of Microflows_InputParameter
	 */
	public final java.util.List<mxmodelreflection.proxies.Parameter> getMicroflows_InputParameter() throws CoreException
	{
		return getMicroflows_InputParameter(getContext());
	}

	/**
	 * @param context
	 * @return value of Microflows_InputParameter
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<mxmodelreflection.proxies.Parameter> getMicroflows_InputParameter(IContext context) throws CoreException
	{
		java.util.List<mxmodelreflection.proxies.Parameter> result = new java.util.ArrayList<mxmodelreflection.proxies.Parameter>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Microflows_InputParameter.toString());
		if (valueObject == null)
			return result;
		for (IMendixObject mendixObject : Core.retrieveIdList(context, (java.util.List<IMendixIdentifier>) valueObject))
			result.add(mxmodelreflection.proxies.Parameter.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of Microflows_InputParameter
	 * @param microflows_inputparameter
	 */
	public final void setMicroflows_InputParameter(java.util.List<mxmodelreflection.proxies.Parameter> microflows_inputparameter)
	{
		setMicroflows_InputParameter(getContext(), microflows_inputparameter);
	}

	/**
	 * Set value of Microflows_InputParameter
	 * @param context
	 * @param microflows_inputparameter
	 */
	public final void setMicroflows_InputParameter(IContext context, java.util.List<mxmodelreflection.proxies.Parameter> microflows_inputparameter)
	{
		java.util.List<IMendixIdentifier> identifiers = new java.util.ArrayList<IMendixIdentifier>();
		for (mxmodelreflection.proxies.Parameter proxyObject : microflows_inputparameter)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.Microflows_InputParameter.toString(), identifiers);
	}

	/**
	 * @return value of Microflows_Output_Type
	 */
	public final mxmodelreflection.proxies.ValueType getMicroflows_Output_Type() throws CoreException
	{
		return getMicroflows_Output_Type(getContext());
	}

	/**
	 * @param context
	 * @return value of Microflows_Output_Type
	 */
	public final mxmodelreflection.proxies.ValueType getMicroflows_Output_Type(IContext context) throws CoreException
	{
		mxmodelreflection.proxies.ValueType result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Microflows_Output_Type.toString());
		if (identifier != null)
			result = mxmodelreflection.proxies.ValueType.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Microflows_Output_Type
	 * @param microflows_output_type
	 */
	public final void setMicroflows_Output_Type(mxmodelreflection.proxies.ValueType microflows_output_type)
	{
		setMicroflows_Output_Type(getContext(), microflows_output_type);
	}

	/**
	 * Set value of Microflows_Output_Type
	 * @param context
	 * @param microflows_output_type
	 */
	public final void setMicroflows_Output_Type(IContext context, mxmodelreflection.proxies.ValueType microflows_output_type)
	{
		if (microflows_output_type == null)
			getMendixObject().setValue(context, MemberNames.Microflows_Output_Type.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Microflows_Output_Type.toString(), microflows_output_type.getMendixObject().getId());
	}

	/**
	 * @return value of Microflows_Module
	 */
	public final mxmodelreflection.proxies.Module getMicroflows_Module() throws CoreException
	{
		return getMicroflows_Module(getContext());
	}

	/**
	 * @param context
	 * @return value of Microflows_Module
	 */
	public final mxmodelreflection.proxies.Module getMicroflows_Module(IContext context) throws CoreException
	{
		mxmodelreflection.proxies.Module result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Microflows_Module.toString());
		if (identifier != null)
			result = mxmodelreflection.proxies.Module.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Microflows_Module
	 * @param microflows_module
	 */
	public final void setMicroflows_Module(mxmodelreflection.proxies.Module microflows_module)
	{
		setMicroflows_Module(getContext(), microflows_module);
	}

	/**
	 * Set value of Microflows_Module
	 * @param context
	 * @param microflows_module
	 */
	public final void setMicroflows_Module(IContext context, mxmodelreflection.proxies.Module microflows_module)
	{
		if (microflows_module == null)
			getMendixObject().setValue(context, MemberNames.Microflows_Module.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Microflows_Module.toString(), microflows_module.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return microflowsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mxmodelreflection.proxies.Microflows that = (mxmodelreflection.proxies.Microflows) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "MxModelReflection.Microflows";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
