// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxmodelreflection.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class Module
{
	private final IMendixObject moduleMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "MxModelReflection.Module";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ModuleName("ModuleName"),
		SynchronizeObjectsWithinModule("SynchronizeObjectsWithinModule");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public Module(IContext context)
	{
		this(context, Core.instantiate(context, "MxModelReflection.Module"));
	}

	protected Module(IContext context, IMendixObject moduleMendixObject)
	{
		if (moduleMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("MxModelReflection.Module", moduleMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a MxModelReflection.Module");

		this.moduleMendixObject = moduleMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Module.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static mxmodelreflection.proxies.Module initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return mxmodelreflection.proxies.Module.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static mxmodelreflection.proxies.Module initialize(IContext context, IMendixObject mendixObject)
	{
		return new mxmodelreflection.proxies.Module(context, mendixObject);
	}

	public static mxmodelreflection.proxies.Module load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return mxmodelreflection.proxies.Module.initialize(context, mendixObject);
	}

	public static java.util.List<mxmodelreflection.proxies.Module> load(IContext context, String xpathConstraint) throws CoreException
	{
		java.util.List<mxmodelreflection.proxies.Module> result = new java.util.ArrayList<mxmodelreflection.proxies.Module>();
		for (IMendixObject obj : Core.retrieveXPathQuery(context, "//MxModelReflection.Module" + xpathConstraint))
			result.add(mxmodelreflection.proxies.Module.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ModuleName
	 */
	public final String getModuleName()
	{
		return getModuleName(getContext());
	}

	/**
	 * @param context
	 * @return value of ModuleName
	 */
	public final String getModuleName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.ModuleName.toString());
	}

	/**
	 * Set value of ModuleName
	 * @param modulename
	 */
	public final void setModuleName(String modulename)
	{
		setModuleName(getContext(), modulename);
	}

	/**
	 * Set value of ModuleName
	 * @param context
	 * @param modulename
	 */
	public final void setModuleName(IContext context, String modulename)
	{
		getMendixObject().setValue(context, MemberNames.ModuleName.toString(), modulename);
	}

	/**
	 * @return value of SynchronizeObjectsWithinModule
	 */
	public final Boolean getSynchronizeObjectsWithinModule()
	{
		return getSynchronizeObjectsWithinModule(getContext());
	}

	/**
	 * @param context
	 * @return value of SynchronizeObjectsWithinModule
	 */
	public final Boolean getSynchronizeObjectsWithinModule(IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.SynchronizeObjectsWithinModule.toString());
	}

	/**
	 * Set value of SynchronizeObjectsWithinModule
	 * @param synchronizeobjectswithinmodule
	 */
	public final void setSynchronizeObjectsWithinModule(Boolean synchronizeobjectswithinmodule)
	{
		setSynchronizeObjectsWithinModule(getContext(), synchronizeobjectswithinmodule);
	}

	/**
	 * Set value of SynchronizeObjectsWithinModule
	 * @param context
	 * @param synchronizeobjectswithinmodule
	 */
	public final void setSynchronizeObjectsWithinModule(IContext context, Boolean synchronizeobjectswithinmodule)
	{
		getMendixObject().setValue(context, MemberNames.SynchronizeObjectsWithinModule.toString(), synchronizeobjectswithinmodule);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return moduleMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mxmodelreflection.proxies.Module that = (mxmodelreflection.proxies.Module) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "MxModelReflection.Module";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
