// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxmodelreflection.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class MxObjectType
{
	private final IMendixObject mxObjectTypeMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "MxModelReflection.MxObjectType";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CompleteName("CompleteName"),
		Name("Name"),
		Module("Module"),
		ReadableName("ReadableName"),
		PersistenceType("PersistenceType"),
		MxObjectType_SubClassOf_MxObjectType("MxModelReflection.MxObjectType_SubClassOf_MxObjectType"),
		MxObjectType_Module("MxModelReflection.MxObjectType_Module");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public MxObjectType(IContext context)
	{
		this(context, Core.instantiate(context, "MxModelReflection.MxObjectType"));
	}

	protected MxObjectType(IContext context, IMendixObject mxObjectTypeMendixObject)
	{
		if (mxObjectTypeMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("MxModelReflection.MxObjectType", mxObjectTypeMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a MxModelReflection.MxObjectType");

		this.mxObjectTypeMendixObject = mxObjectTypeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MxObjectType.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static mxmodelreflection.proxies.MxObjectType initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return mxmodelreflection.proxies.MxObjectType.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static mxmodelreflection.proxies.MxObjectType initialize(IContext context, IMendixObject mendixObject)
	{
		return new mxmodelreflection.proxies.MxObjectType(context, mendixObject);
	}

	public static mxmodelreflection.proxies.MxObjectType load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return mxmodelreflection.proxies.MxObjectType.initialize(context, mendixObject);
	}

	public static java.util.List<mxmodelreflection.proxies.MxObjectType> load(IContext context, String xpathConstraint) throws CoreException
	{
		java.util.List<mxmodelreflection.proxies.MxObjectType> result = new java.util.ArrayList<mxmodelreflection.proxies.MxObjectType>();
		for (IMendixObject obj : Core.retrieveXPathQuery(context, "//MxModelReflection.MxObjectType" + xpathConstraint))
			result.add(mxmodelreflection.proxies.MxObjectType.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of CompleteName
	 */
	public final String getCompleteName()
	{
		return getCompleteName(getContext());
	}

	/**
	 * @param context
	 * @return value of CompleteName
	 */
	public final String getCompleteName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.CompleteName.toString());
	}

	/**
	 * Set value of CompleteName
	 * @param completename
	 */
	public final void setCompleteName(String completename)
	{
		setCompleteName(getContext(), completename);
	}

	/**
	 * Set value of CompleteName
	 * @param context
	 * @param completename
	 */
	public final void setCompleteName(IContext context, String completename)
	{
		getMendixObject().setValue(context, MemberNames.CompleteName.toString(), completename);
	}

	/**
	 * @return value of Name
	 */
	public final String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final String getName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(IContext context, String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Module
	 */
	public final String getModule()
	{
		return getModule(getContext());
	}

	/**
	 * @param context
	 * @return value of Module
	 */
	public final String getModule(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Module.toString());
	}

	/**
	 * Set value of Module
	 * @param module
	 */
	public final void setModule(String module)
	{
		setModule(getContext(), module);
	}

	/**
	 * Set value of Module
	 * @param context
	 * @param module
	 */
	public final void setModule(IContext context, String module)
	{
		getMendixObject().setValue(context, MemberNames.Module.toString(), module);
	}

	/**
	 * @return value of ReadableName
	 */
	public final String getReadableName()
	{
		return getReadableName(getContext());
	}

	/**
	 * @param context
	 * @return value of ReadableName
	 */
	public final String getReadableName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.ReadableName.toString());
	}

	/**
	 * Set value of ReadableName
	 * @param readablename
	 */
	public final void setReadableName(String readablename)
	{
		setReadableName(getContext(), readablename);
	}

	/**
	 * Set value of ReadableName
	 * @param context
	 * @param readablename
	 */
	public final void setReadableName(IContext context, String readablename)
	{
		getMendixObject().setValue(context, MemberNames.ReadableName.toString(), readablename);
	}

	/**
	 * Set value of PersistenceType
	 * @param persistencetype
	 */
	public final mxmodelreflection.proxies.PersistenceType getPersistenceType()
	{
		return getPersistenceType(getContext());
	}

	/**
	 * @param context
	 * @return value of PersistenceType
	 */
	public final mxmodelreflection.proxies.PersistenceType getPersistenceType(IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.PersistenceType.toString());
		if (obj == null)
			return null;

		return mxmodelreflection.proxies.PersistenceType.valueOf((String) obj);
	}

	/**
	 * Set value of PersistenceType
	 * @param persistencetype
	 */
	public final void setPersistenceType(mxmodelreflection.proxies.PersistenceType persistencetype)
	{
		setPersistenceType(getContext(), persistencetype);
	}

	/**
	 * Set value of PersistenceType
	 * @param context
	 * @param persistencetype
	 */
	public final void setPersistenceType(IContext context, mxmodelreflection.proxies.PersistenceType persistencetype)
	{
		if (persistencetype != null)
			getMendixObject().setValue(context, MemberNames.PersistenceType.toString(), persistencetype.toString());
		else
			getMendixObject().setValue(context, MemberNames.PersistenceType.toString(), null);
	}

	/**
	 * @return value of MxObjectType_SubClassOf_MxObjectType
	 */
	public final java.util.List<mxmodelreflection.proxies.MxObjectType> getMxObjectType_SubClassOf_MxObjectType() throws CoreException
	{
		return getMxObjectType_SubClassOf_MxObjectType(getContext());
	}

	/**
	 * @param context
	 * @return value of MxObjectType_SubClassOf_MxObjectType
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<mxmodelreflection.proxies.MxObjectType> getMxObjectType_SubClassOf_MxObjectType(IContext context) throws CoreException
	{
		java.util.List<mxmodelreflection.proxies.MxObjectType> result = new java.util.ArrayList<mxmodelreflection.proxies.MxObjectType>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.MxObjectType_SubClassOf_MxObjectType.toString());
		if (valueObject == null)
			return result;
		for (IMendixObject mendixObject : Core.retrieveIdList(context, (java.util.List<IMendixIdentifier>) valueObject))
			result.add(mxmodelreflection.proxies.MxObjectType.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of MxObjectType_SubClassOf_MxObjectType
	 * @param mxobjecttype_subclassof_mxobjecttype
	 */
	public final void setMxObjectType_SubClassOf_MxObjectType(java.util.List<mxmodelreflection.proxies.MxObjectType> mxobjecttype_subclassof_mxobjecttype)
	{
		setMxObjectType_SubClassOf_MxObjectType(getContext(), mxobjecttype_subclassof_mxobjecttype);
	}

	/**
	 * Set value of MxObjectType_SubClassOf_MxObjectType
	 * @param context
	 * @param mxobjecttype_subclassof_mxobjecttype
	 */
	public final void setMxObjectType_SubClassOf_MxObjectType(IContext context, java.util.List<mxmodelreflection.proxies.MxObjectType> mxobjecttype_subclassof_mxobjecttype)
	{
		java.util.List<IMendixIdentifier> identifiers = new java.util.ArrayList<IMendixIdentifier>();
		for (mxmodelreflection.proxies.MxObjectType proxyObject : mxobjecttype_subclassof_mxobjecttype)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.MxObjectType_SubClassOf_MxObjectType.toString(), identifiers);
	}

	/**
	 * @return value of MxObjectType_Module
	 */
	public final mxmodelreflection.proxies.Module getMxObjectType_Module() throws CoreException
	{
		return getMxObjectType_Module(getContext());
	}

	/**
	 * @param context
	 * @return value of MxObjectType_Module
	 */
	public final mxmodelreflection.proxies.Module getMxObjectType_Module(IContext context) throws CoreException
	{
		mxmodelreflection.proxies.Module result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MxObjectType_Module.toString());
		if (identifier != null)
			result = mxmodelreflection.proxies.Module.load(context, identifier);
		return result;
	}

	/**
	 * Set value of MxObjectType_Module
	 * @param mxobjecttype_module
	 */
	public final void setMxObjectType_Module(mxmodelreflection.proxies.Module mxobjecttype_module)
	{
		setMxObjectType_Module(getContext(), mxobjecttype_module);
	}

	/**
	 * Set value of MxObjectType_Module
	 * @param context
	 * @param mxobjecttype_module
	 */
	public final void setMxObjectType_Module(IContext context, mxmodelreflection.proxies.Module mxobjecttype_module)
	{
		if (mxobjecttype_module == null)
			getMendixObject().setValue(context, MemberNames.MxObjectType_Module.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.MxObjectType_Module.toString(), mxobjecttype_module.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return mxObjectTypeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mxmodelreflection.proxies.MxObjectType that = (mxmodelreflection.proxies.MxObjectType) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "MxModelReflection.MxObjectType";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
