// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package encryption.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class PasswordData
{
	private final IMendixObject passwordDataMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "Encryption.PasswordData";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NewPassword("NewPassword"),
		ConfirmPassword("ConfirmPassword"),
		PasswordData_ExampleConfiguration("Encryption.PasswordData_ExampleConfiguration");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public PasswordData(IContext context)
	{
		this(context, Core.instantiate(context, "Encryption.PasswordData"));
	}

	protected PasswordData(IContext context, IMendixObject passwordDataMendixObject)
	{
		if (passwordDataMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("Encryption.PasswordData", passwordDataMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a Encryption.PasswordData");

		this.passwordDataMendixObject = passwordDataMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PasswordData.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static encryption.proxies.PasswordData initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return encryption.proxies.PasswordData.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static encryption.proxies.PasswordData initialize(IContext context, IMendixObject mendixObject)
	{
		return new encryption.proxies.PasswordData(context, mendixObject);
	}

	public static encryption.proxies.PasswordData load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return encryption.proxies.PasswordData.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of NewPassword
	 */
	public final String getNewPassword()
	{
		return getNewPassword(getContext());
	}

	/**
	 * @param context
	 * @return value of NewPassword
	 */
	public final String getNewPassword(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.NewPassword.toString());
	}

	/**
	 * Set value of NewPassword
	 * @param newpassword
	 */
	public final void setNewPassword(String newpassword)
	{
		setNewPassword(getContext(), newpassword);
	}

	/**
	 * Set value of NewPassword
	 * @param context
	 * @param newpassword
	 */
	public final void setNewPassword(IContext context, String newpassword)
	{
		getMendixObject().setValue(context, MemberNames.NewPassword.toString(), newpassword);
	}

	/**
	 * @return value of ConfirmPassword
	 */
	public final String getConfirmPassword()
	{
		return getConfirmPassword(getContext());
	}

	/**
	 * @param context
	 * @return value of ConfirmPassword
	 */
	public final String getConfirmPassword(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.ConfirmPassword.toString());
	}

	/**
	 * Set value of ConfirmPassword
	 * @param confirmpassword
	 */
	public final void setConfirmPassword(String confirmpassword)
	{
		setConfirmPassword(getContext(), confirmpassword);
	}

	/**
	 * Set value of ConfirmPassword
	 * @param context
	 * @param confirmpassword
	 */
	public final void setConfirmPassword(IContext context, String confirmpassword)
	{
		getMendixObject().setValue(context, MemberNames.ConfirmPassword.toString(), confirmpassword);
	}

	/**
	 * @return value of PasswordData_ExampleConfiguration
	 */
	public final encryption.proxies.ExampleConfiguration getPasswordData_ExampleConfiguration() throws CoreException
	{
		return getPasswordData_ExampleConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of PasswordData_ExampleConfiguration
	 */
	public final encryption.proxies.ExampleConfiguration getPasswordData_ExampleConfiguration(IContext context) throws CoreException
	{
		encryption.proxies.ExampleConfiguration result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PasswordData_ExampleConfiguration.toString());
		if (identifier != null)
			result = encryption.proxies.ExampleConfiguration.load(context, identifier);
		return result;
	}

	/**
	 * Set value of PasswordData_ExampleConfiguration
	 * @param passworddata_exampleconfiguration
	 */
	public final void setPasswordData_ExampleConfiguration(encryption.proxies.ExampleConfiguration passworddata_exampleconfiguration)
	{
		setPasswordData_ExampleConfiguration(getContext(), passworddata_exampleconfiguration);
	}

	/**
	 * Set value of PasswordData_ExampleConfiguration
	 * @param context
	 * @param passworddata_exampleconfiguration
	 */
	public final void setPasswordData_ExampleConfiguration(IContext context, encryption.proxies.ExampleConfiguration passworddata_exampleconfiguration)
	{
		if (passworddata_exampleconfiguration == null)
			getMendixObject().setValue(context, MemberNames.PasswordData_ExampleConfiguration.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.PasswordData_ExampleConfiguration.toString(), passworddata_exampleconfiguration.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return passwordDataMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final encryption.proxies.PasswordData that = (encryption.proxies.PasswordData) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "Encryption.PasswordData";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
