// This file was generated by Mendix Modeler 6.8.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emailtemplate.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the EmailTemplate module
	public static boolean bCo_EmailSettings(IContext context, emailtemplate.proxies.EmailSettings _emailSettings)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("EmailSettings", _emailSettings == null ? null : _emailSettings.getMendixObject());
			return (Boolean)Core.execute(context, "EmailTemplate.BCo_EmailSettings", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static emailtemplate.proxies.EmailSettings dS_GetEmailSettings(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "EmailTemplate.DS_GetEmailSettings", params);
			return result == null ? null : emailtemplate.proxies.EmailSettings.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_DownloadAttachment(IContext context, emailtemplate.proxies.Attachment _attachment)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Attachment", _attachment == null ? null : _attachment.getMendixObject());
			Core.execute(context, "EmailTemplate.IVK_DownloadAttachment", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_DuplicateEmailTemplate(IContext context, emailtemplate.proxies.EmailTemplate _emailTemplate)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("EmailTemplate", _emailTemplate == null ? null : _emailTemplate.getMendixObject());
			Core.execute(context, "EmailTemplate.IVK_DuplicateEmailTemplate", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_Emailtemplate_NewToken(IContext context, emailtemplate.proxies.EmailTemplate _emailTemplate)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("EmailTemplate", _emailTemplate == null ? null : _emailTemplate.getMendixObject());
			Core.execute(context, "EmailTemplate.IVK_Emailtemplate_NewToken", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_GeneratePlainText(IContext context, emailtemplate.proxies.EmailTemplate _emailTemplate)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("EmailTemplate", _emailTemplate == null ? null : _emailTemplate.getMendixObject());
			Core.execute(context, "EmailTemplate.IVK_GeneratePlainText", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_ResendFailedEmail(IContext context, emailtemplate.proxies.Email _email)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Email", _email == null ? null : _email.getMendixObject());
			Core.execute(context, "EmailTemplate.IVK_ResendFailedEmail", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_ResendFailedEmails(IContext context, java.util.List<emailtemplate.proxies.Email> _emailList)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			java.util.ArrayList<IMendixObject> listparam_emailList = null;
			if (_emailList != null)
			{
				listparam_emailList = new java.util.ArrayList<IMendixObject>();
				for (emailtemplate.proxies.Email obj : _emailList)
					listparam_emailList.add(obj.getMendixObject());
			}
			params.put("EmailList", listparam_emailList);
			Core.execute(context, "EmailTemplate.IVK_ResendFailedEmails", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_SaveEmailSettings(IContext context, emailtemplate.proxies.EmailSettings _emailSettings)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("EmailSettings", _emailSettings == null ? null : _emailSettings.getMendixObject());
			Core.execute(context, "EmailTemplate.IVK_SaveEmailSettings", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_SaveEmailTemplate(IContext context, emailtemplate.proxies.EmailTemplate _emailTemplate)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("EmailTemplate", _emailTemplate == null ? null : _emailTemplate.getMendixObject());
			Core.execute(context, "EmailTemplate.IVK_SaveEmailTemplate", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void oC_SSL(IContext context, emailtemplate.proxies.EmailSettings _emailSettings)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("EmailSettings", _emailSettings == null ? null : _emailSettings.getMendixObject());
			Core.execute(context, "EmailTemplate.OC_SSL", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void oC_TLS(IContext context, emailtemplate.proxies.EmailSettings _emailSettings)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("EmailSettings", _emailSettings == null ? null : _emailSettings.getMendixObject());
			Core.execute(context, "EmailTemplate.OC_TLS", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void sE_Cleanup(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			Core.execute(context, "EmailTemplate.SE_Cleanup", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void sE_SendQueuedEmails(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			Core.execute(context, "EmailTemplate.SE_SendQueuedEmails", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<emailtemplate.proxies.Attachment> sub_CreateAttachments(IContext context, java.util.List<system.proxies.FileDocument> _fileDocumentList, emailtemplate.proxies.Email _email)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			java.util.ArrayList<IMendixObject> listparam_fileDocumentList = null;
			if (_fileDocumentList != null)
			{
				listparam_fileDocumentList = new java.util.ArrayList<IMendixObject>();
				for (system.proxies.FileDocument obj : _fileDocumentList)
					listparam_fileDocumentList.add(obj.getMendixObject());
			}
			params.put("FileDocumentList", listparam_fileDocumentList);
			params.put("Email", _email == null ? null : _email.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "EmailTemplate.Sub_CreateAttachments", params);
			java.util.List<emailtemplate.proxies.Attachment> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<emailtemplate.proxies.Attachment>();
				for (IMendixObject obj : objs)
					result.add(emailtemplate.proxies.Attachment.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void sub_CreateLogItem(IContext context, String _triggeredInMF, emailtemplate.proxies.LogType _logType, String _message, String _errorMessage, String _stackTrace)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("TriggeredInMF", _triggeredInMF);
			params.put("LogType", _logType == null ? null : _logType.name());
			params.put("Message", _message);
			params.put("ErrorMessage", _errorMessage);
			params.put("StackTrace", _stackTrace);
			Core.execute(context, "EmailTemplate.Sub_CreateLogItem", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<mxmodelreflection.proxies.Token> sub_DuplicateTokenList(IContext context, java.util.List<mxmodelreflection.proxies.Token> _tokenList)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			java.util.ArrayList<IMendixObject> listparam_tokenList = null;
			if (_tokenList != null)
			{
				listparam_tokenList = new java.util.ArrayList<IMendixObject>();
				for (mxmodelreflection.proxies.Token obj : _tokenList)
					listparam_tokenList.add(obj.getMendixObject());
			}
			params.put("TokenList", listparam_tokenList);
			java.util.List<IMendixObject> objs = Core.execute(context, "EmailTemplate.Sub_DuplicateTokenList", params);
			java.util.List<mxmodelreflection.proxies.Token> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<mxmodelreflection.proxies.Token>();
				for (IMendixObject obj : objs)
					result.add(mxmodelreflection.proxies.Token.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void sub_SendQueuedEmail(IContext context, emailtemplate.proxies.Email _email, emailtemplate.proxies.EmailSettings _emailSettings, String _decryptedPassword)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Email", _email == null ? null : _email.getMendixObject());
			params.put("EmailSettings", _emailSettings == null ? null : _emailSettings.getMendixObject());
			params.put("DecryptedPassword", _decryptedPassword);
			Core.execute(context, "EmailTemplate.Sub_SendQueuedEmail", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}