// This file was generated by Mendix Business Modeler 5.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package encryption.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the Encryption module

	public static String getEncryptionKey()
	{
		return (String)Core.getConfiguration().getConstantValue("Encryption.EncryptionKey");
	}

	public static String getEncryptionPrefix()
	{
		return (String)Core.getConfiguration().getConstantValue("Encryption.EncryptionPrefix");
	}

	public static String getLogNode()
	{
		return (String)Core.getConfiguration().getConstantValue("Encryption.LogNode");
	}
}