// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package googlecharts.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class BooleanValue extends googlecharts.proxies.Cell
{
	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "GoogleCharts.BooleanValue";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		v("v");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public BooleanValue(IContext context)
	{
		this(context, Core.instantiate(context, "GoogleCharts.BooleanValue"));
	}

	protected BooleanValue(IContext context, IMendixObject booleanValueMendixObject)
	{
		super(context, booleanValueMendixObject);
		if (!Core.isSubClassOf("GoogleCharts.BooleanValue", booleanValueMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a GoogleCharts.BooleanValue");
	}

	/**
	 * @deprecated Use 'BooleanValue.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static googlecharts.proxies.BooleanValue initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return googlecharts.proxies.BooleanValue.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static googlecharts.proxies.BooleanValue initialize(IContext context, IMendixObject mendixObject)
	{
		return new googlecharts.proxies.BooleanValue(context, mendixObject);
	}

	public static googlecharts.proxies.BooleanValue load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return googlecharts.proxies.BooleanValue.initialize(context, mendixObject);
	}

	/**
	 * @return value of v
	 */
	public final Boolean getv()
	{
		return getv(getContext());
	}

	/**
	 * @param context
	 * @return value of v
	 */
	public final Boolean getv(IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.v.toString());
	}

	/**
	 * Set value of v
	 * @param v
	 */
	public final void setv(Boolean v)
	{
		setv(getContext(), v);
	}

	/**
	 * Set value of v
	 * @param context
	 * @param v
	 */
	public final void setv(IContext context, Boolean v)
	{
		getMendixObject().setValue(context, MemberNames.v.toString(), v);
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final googlecharts.proxies.BooleanValue that = (googlecharts.proxies.BooleanValue) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "GoogleCharts.BooleanValue";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
