// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package googlecharts.proxies;

public class Bpi
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject bpiMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GoogleCharts.Bpi";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_2013_09_01("_2013_09_01"),
		_2013_09_02("_2013_09_02"),
		_2013_09_03("_2013_09_03"),
		_2013_09_04("_2013_09_04"),
		_2013_09_05("_2013_09_05"),
		Bpi_Root("GoogleCharts.Bpi_Root");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Bpi(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "GoogleCharts.Bpi"));
	}

	protected Bpi(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject bpiMendixObject)
	{
		if (bpiMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("GoogleCharts.Bpi", bpiMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a GoogleCharts.Bpi");

		this.bpiMendixObject = bpiMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Bpi.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static googlecharts.proxies.Bpi initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return googlecharts.proxies.Bpi.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static googlecharts.proxies.Bpi initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new googlecharts.proxies.Bpi(context, mendixObject);
	}

	public static googlecharts.proxies.Bpi load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return googlecharts.proxies.Bpi.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _2013_09_01
	 */
	public final java.math.BigDecimal get_2013_09_01()
	{
		return get_2013_09_01(getContext());
	}

	/**
	 * @param context
	 * @return value of _2013_09_01
	 */
	public final java.math.BigDecimal get_2013_09_01(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames._2013_09_01.toString());
	}

	/**
	 * Set value of _2013_09_01
	 * @param _2013_09_01
	 */
	public final void set_2013_09_01(java.math.BigDecimal _2013_09_01)
	{
		set_2013_09_01(getContext(), _2013_09_01);
	}

	/**
	 * Set value of _2013_09_01
	 * @param context
	 * @param _2013_09_01
	 */
	public final void set_2013_09_01(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal _2013_09_01)
	{
		getMendixObject().setValue(context, MemberNames._2013_09_01.toString(), _2013_09_01);
	}

	/**
	 * @return value of _2013_09_02
	 */
	public final java.math.BigDecimal get_2013_09_02()
	{
		return get_2013_09_02(getContext());
	}

	/**
	 * @param context
	 * @return value of _2013_09_02
	 */
	public final java.math.BigDecimal get_2013_09_02(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames._2013_09_02.toString());
	}

	/**
	 * Set value of _2013_09_02
	 * @param _2013_09_02
	 */
	public final void set_2013_09_02(java.math.BigDecimal _2013_09_02)
	{
		set_2013_09_02(getContext(), _2013_09_02);
	}

	/**
	 * Set value of _2013_09_02
	 * @param context
	 * @param _2013_09_02
	 */
	public final void set_2013_09_02(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal _2013_09_02)
	{
		getMendixObject().setValue(context, MemberNames._2013_09_02.toString(), _2013_09_02);
	}

	/**
	 * @return value of _2013_09_03
	 */
	public final java.math.BigDecimal get_2013_09_03()
	{
		return get_2013_09_03(getContext());
	}

	/**
	 * @param context
	 * @return value of _2013_09_03
	 */
	public final java.math.BigDecimal get_2013_09_03(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames._2013_09_03.toString());
	}

	/**
	 * Set value of _2013_09_03
	 * @param _2013_09_03
	 */
	public final void set_2013_09_03(java.math.BigDecimal _2013_09_03)
	{
		set_2013_09_03(getContext(), _2013_09_03);
	}

	/**
	 * Set value of _2013_09_03
	 * @param context
	 * @param _2013_09_03
	 */
	public final void set_2013_09_03(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal _2013_09_03)
	{
		getMendixObject().setValue(context, MemberNames._2013_09_03.toString(), _2013_09_03);
	}

	/**
	 * @return value of _2013_09_04
	 */
	public final java.math.BigDecimal get_2013_09_04()
	{
		return get_2013_09_04(getContext());
	}

	/**
	 * @param context
	 * @return value of _2013_09_04
	 */
	public final java.math.BigDecimal get_2013_09_04(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames._2013_09_04.toString());
	}

	/**
	 * Set value of _2013_09_04
	 * @param _2013_09_04
	 */
	public final void set_2013_09_04(java.math.BigDecimal _2013_09_04)
	{
		set_2013_09_04(getContext(), _2013_09_04);
	}

	/**
	 * Set value of _2013_09_04
	 * @param context
	 * @param _2013_09_04
	 */
	public final void set_2013_09_04(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal _2013_09_04)
	{
		getMendixObject().setValue(context, MemberNames._2013_09_04.toString(), _2013_09_04);
	}

	/**
	 * @return value of _2013_09_05
	 */
	public final java.math.BigDecimal get_2013_09_05()
	{
		return get_2013_09_05(getContext());
	}

	/**
	 * @param context
	 * @return value of _2013_09_05
	 */
	public final java.math.BigDecimal get_2013_09_05(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames._2013_09_05.toString());
	}

	/**
	 * Set value of _2013_09_05
	 * @param _2013_09_05
	 */
	public final void set_2013_09_05(java.math.BigDecimal _2013_09_05)
	{
		set_2013_09_05(getContext(), _2013_09_05);
	}

	/**
	 * Set value of _2013_09_05
	 * @param context
	 * @param _2013_09_05
	 */
	public final void set_2013_09_05(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal _2013_09_05)
	{
		getMendixObject().setValue(context, MemberNames._2013_09_05.toString(), _2013_09_05);
	}

	/**
	 * @return value of Bpi_Root
	 */
	public final googlecharts.proxies.Root getBpi_Root() throws com.mendix.core.CoreException
	{
		return getBpi_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Bpi_Root
	 */
	public final googlecharts.proxies.Root getBpi_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		googlecharts.proxies.Root result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Bpi_Root.toString());
		if (identifier != null)
			result = googlecharts.proxies.Root.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Bpi_Root
	 * @param bpi_root
	 */
	public final void setBpi_Root(googlecharts.proxies.Root bpi_root)
	{
		setBpi_Root(getContext(), bpi_root);
	}

	/**
	 * Set value of Bpi_Root
	 * @param context
	 * @param bpi_root
	 */
	public final void setBpi_Root(com.mendix.systemwideinterfaces.core.IContext context, googlecharts.proxies.Root bpi_root)
	{
		if (bpi_root == null)
			getMendixObject().setValue(context, MemberNames.Bpi_Root.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Bpi_Root.toString(), bpi_root.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return bpiMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final googlecharts.proxies.Bpi that = (googlecharts.proxies.Bpi) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "GoogleCharts.Bpi";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
