// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package googlecharts.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class Column
{
	private final IMendixObject columnMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "GoogleCharts.Column";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		label("label"),
		_type("_type"),
		_type_jsonkey("_type_jsonkey");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public Column(IContext context)
	{
		this(context, Core.instantiate(context, "GoogleCharts.Column"));
	}

	protected Column(IContext context, IMendixObject columnMendixObject)
	{
		if (columnMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("GoogleCharts.Column", columnMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a GoogleCharts.Column");

		this.columnMendixObject = columnMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Column.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static googlecharts.proxies.Column initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return googlecharts.proxies.Column.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static googlecharts.proxies.Column initialize(IContext context, IMendixObject mendixObject)
	{
		return new googlecharts.proxies.Column(context, mendixObject);
	}

	public static googlecharts.proxies.Column load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return googlecharts.proxies.Column.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of label
	 */
	public final String getlabel()
	{
		return getlabel(getContext());
	}

	/**
	 * @param context
	 * @return value of label
	 */
	public final String getlabel(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.label.toString());
	}

	/**
	 * Set value of label
	 * @param label
	 */
	public final void setlabel(String label)
	{
		setlabel(getContext(), label);
	}

	/**
	 * Set value of label
	 * @param context
	 * @param label
	 */
	public final void setlabel(IContext context, String label)
	{
		getMendixObject().setValue(context, MemberNames.label.toString(), label);
	}

	/**
	 * @return value of _type
	 */
	public final String get_type()
	{
		return get_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _type
	 */
	public final String get_type(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames._type.toString());
	}

	/**
	 * Set value of _type
	 * @param _type
	 */
	public final void set_type(String _type)
	{
		set_type(getContext(), _type);
	}

	/**
	 * Set value of _type
	 * @param context
	 * @param _type
	 */
	public final void set_type(IContext context, String _type)
	{
		getMendixObject().setValue(context, MemberNames._type.toString(), _type);
	}

	/**
	 * @return value of _type_jsonkey
	 */
	public final String get_type_jsonkey()
	{
		return get_type_jsonkey(getContext());
	}

	/**
	 * @param context
	 * @return value of _type_jsonkey
	 */
	public final String get_type_jsonkey(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames._type_jsonkey.toString());
	}

	/**
	 * Set value of _type_jsonkey
	 * @param _type_jsonkey
	 */
	public final void set_type_jsonkey(String _type_jsonkey)
	{
		set_type_jsonkey(getContext(), _type_jsonkey);
	}

	/**
	 * Set value of _type_jsonkey
	 * @param context
	 * @param _type_jsonkey
	 */
	public final void set_type_jsonkey(IContext context, String _type_jsonkey)
	{
		getMendixObject().setValue(context, MemberNames._type_jsonkey.toString(), _type_jsonkey);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return columnMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final googlecharts.proxies.Column that = (googlecharts.proxies.Column) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "GoogleCharts.Column";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
