// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package googlecharts.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class StringValue extends googlecharts.proxies.Cell
{
	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "GoogleCharts.StringValue";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		v("v");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public StringValue(IContext context)
	{
		this(context, Core.instantiate(context, "GoogleCharts.StringValue"));
	}

	protected StringValue(IContext context, IMendixObject stringValueMendixObject)
	{
		super(context, stringValueMendixObject);
		if (!Core.isSubClassOf("GoogleCharts.StringValue", stringValueMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a GoogleCharts.StringValue");
	}

	/**
	 * @deprecated Use 'StringValue.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static googlecharts.proxies.StringValue initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return googlecharts.proxies.StringValue.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static googlecharts.proxies.StringValue initialize(IContext context, IMendixObject mendixObject)
	{
		return new googlecharts.proxies.StringValue(context, mendixObject);
	}

	public static googlecharts.proxies.StringValue load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return googlecharts.proxies.StringValue.initialize(context, mendixObject);
	}

	/**
	 * @return value of v
	 */
	public final String getv()
	{
		return getv(getContext());
	}

	/**
	 * @param context
	 * @return value of v
	 */
	public final String getv(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.v.toString());
	}

	/**
	 * Set value of v
	 * @param v
	 */
	public final void setv(String v)
	{
		setv(getContext(), v);
	}

	/**
	 * Set value of v
	 * @param context
	 * @param v
	 */
	public final void setv(IContext context, String v)
	{
		getMendixObject().setValue(context, MemberNames.v.toString(), v);
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final googlecharts.proxies.StringValue that = (googlecharts.proxies.StringValue) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "GoogleCharts.StringValue";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
