// This file was generated by Mendix Modeler 6.10.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emailtemplate.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the EmailTemplate module

	public static java.lang.String getEmailAddressSeparator()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("EmailTemplate.EmailAddressSeparator");
	}

	/**
	* The amount of days to preserve error messages.
	*/
	public static java.lang.Long getEmailLogRetention()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("EmailTemplate.EmailLogRetention");
	}

	/**
	* The amount of days to preserve emails which were sent.
	*/
	public static java.lang.Long getEmailRetention()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("EmailTemplate.EmailRetention");
	}

	public static java.lang.String getLogNode()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("EmailTemplate.LogNode");
	}
}