// This file was generated by Mendix Business Modeler 5.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emailtemplate.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the EmailTemplate module

	public static String getEmailAddressSeparator()
	{
		return (String)Core.getConfiguration().getConstantValue("EmailTemplate.EmailAddressSeparator");
	}

	public static Long getEmailLogRetention()
	{
		return (Long)Core.getConfiguration().getConstantValue("EmailTemplate.EmailLogRetention");
	}

	public static Long getEmailRetention()
	{
		return (Long)Core.getConfiguration().getConstantValue("EmailTemplate.EmailRetention");
	}

	public static String getLogNode()
	{
		return (String)Core.getConfiguration().getConstantValue("EmailTemplate.LogNode");
	}
}