// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package databasereplication.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import databasereplication.implementation.ObjectBaseDBSettings;
import databasereplication.proxies.Database;

public class EncryptServerPassword extends CustomJavaAction<Boolean>
{
	private IMendixObject DatabaseServer;

	public EncryptServerPassword(IContext context, IMendixObject DatabaseServer)
	{
		super(context);
		this.DatabaseServer = DatabaseServer;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext context = this.getContext();
		String unEncryptedPass = (String) this.DatabaseServer.getValue(context, Database.MemberNames.DatabasePassword.toString());
		if (unEncryptedPass != null && !"ThisIsConvertedToAnEncryptedPass".equals(unEncryptedPass)) {
			this.DatabaseServer.setValue(context, Database.MemberNames.DatabasePassword_Encrypted.toString(), ObjectBaseDBSettings.encryptString(unEncryptedPass));
			this.DatabaseServer.setValue(context, Database.MemberNames.DatabasePassword.toString(), "ThisIsConvertedToAnEncryptedPass");
		}
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "EncryptServerPassword";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
