// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package databasereplication.actions;

import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class UpdateToken extends CustomJavaAction<Boolean>
{
	private IMendixObject __joinObject;
	private databasereplication.proxies.AdditionalJoins joinObject;

	public UpdateToken(IContext context, IMendixObject joinObject)
	{
		super(context);
		this.__joinObject = joinObject;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		this.joinObject = __joinObject == null ? null : databasereplication.proxies.AdditionalJoins.initialize(getContext(), __joinObject);

		// BEGIN USER CODE
		
		if( this.joinObject.getAlias() != null && !"".equals(this.joinObject.getAlias()) ) {
			String token = this.joinObject.getAlias();
			token = token.replace(" ", "");
			token = token.replace("-", "");
			token = token.replace("'", "");
			token = token.replace("\"", "");
			token = "[%" + token + "%]";
			this.joinObject.setToken(token);
		}
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "UpdateToken";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
