// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databasereplication.proxies;

public enum ContraintInputObject
{
	Object1(new String[][] { new String[] { "nl_NL", "Invoer object 1" }, new String[] { "en_US", "Data object 1" }, new String[] { "en_GB", "Data object 1" }, new String[] { "en_ZA", "Data object 1" } }),
	Object2(new String[][] { new String[] { "nl_NL", "Invoer object 2" }, new String[] { "en_US", "Data object 2" }, new String[] { "en_GB", "Data object 2" }, new String[] { "en_ZA", "Data object 2" } });

	private java.util.Map<String,String> captions;

	private ContraintInputObject(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
