// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databasereplication.proxies;

public class CustomConstraint
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject customConstraintMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DatabaseReplication.CustomConstraint";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Nr("Nr"),
		ConstraintType("ConstraintType"),
		Operator("Operator"),
		Value("Value"),
		InputObject("InputObject"),
		Description("Description"),
		Token("Token"),
		IgnoreWhenEmpty("IgnoreWhenEmpty"),
		CustomConstraint_AdditionalJoins("DatabaseReplication.CustomConstraint_AdditionalJoins"),
		CustomConstraint_Column("DatabaseReplication.CustomConstraint_Column"),
		CustomConstraint_ImportCall("DatabaseReplication.CustomConstraint_ImportCall"),
		CustomConstraint_ColumnTemp("DatabaseReplication.CustomConstraint_ColumnTemp"),
		CustomConstraint_AdditionalJoinTemp("DatabaseReplication.CustomConstraint_AdditionalJoinTemp"),
		CustomConstraint_MxObjectMember("DatabaseReplication.CustomConstraint_MxObjectMember");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CustomConstraint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DatabaseReplication.CustomConstraint"));
	}

	protected CustomConstraint(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject customConstraintMendixObject)
	{
		if (customConstraintMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DatabaseReplication.CustomConstraint", customConstraintMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DatabaseReplication.CustomConstraint");

		this.customConstraintMendixObject = customConstraintMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'CustomConstraint.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static databasereplication.proxies.CustomConstraint initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return databasereplication.proxies.CustomConstraint.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static databasereplication.proxies.CustomConstraint initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new databasereplication.proxies.CustomConstraint(context, mendixObject);
	}

	public static databasereplication.proxies.CustomConstraint load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return databasereplication.proxies.CustomConstraint.initialize(context, mendixObject);
	}

	public static java.util.List<databasereplication.proxies.CustomConstraint> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<databasereplication.proxies.CustomConstraint> result = new java.util.ArrayList<databasereplication.proxies.CustomConstraint>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DatabaseReplication.CustomConstraint" + xpathConstraint))
			result.add(databasereplication.proxies.CustomConstraint.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Nr
	 */
	public final Long getNr()
	{
		return getNr(getContext());
	}

	/**
	 * @param context
	 * @return value of Nr
	 */
	public final Long getNr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Long) getMendixObject().getValue(context, MemberNames.Nr.toString());
	}

	/**
	 * Set value of Nr
	 * @param nr
	 */
	public final void setNr(Long nr)
	{
		setNr(getContext(), nr);
	}

	/**
	 * Set value of Nr
	 * @param context
	 * @param nr
	 */
	public final void setNr(com.mendix.systemwideinterfaces.core.IContext context, Long nr)
	{
		getMendixObject().setValue(context, MemberNames.Nr.toString(), nr);
	}

	/**
	 * Set value of ConstraintType
	 * @param constrainttype
	 */
	public final databasereplication.proxies.CustomConstraintType getConstraintType()
	{
		return getConstraintType(getContext());
	}

	/**
	 * @param context
	 * @return value of ConstraintType
	 */
	public final databasereplication.proxies.CustomConstraintType getConstraintType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ConstraintType.toString());
		if (obj == null)
			return null;

		return databasereplication.proxies.CustomConstraintType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ConstraintType
	 * @param constrainttype
	 */
	public final void setConstraintType(databasereplication.proxies.CustomConstraintType constrainttype)
	{
		setConstraintType(getContext(), constrainttype);
	}

	/**
	 * Set value of ConstraintType
	 * @param context
	 * @param constrainttype
	 */
	public final void setConstraintType(com.mendix.systemwideinterfaces.core.IContext context, databasereplication.proxies.CustomConstraintType constrainttype)
	{
		if (constrainttype != null)
			getMendixObject().setValue(context, MemberNames.ConstraintType.toString(), constrainttype.toString());
		else
			getMendixObject().setValue(context, MemberNames.ConstraintType.toString(), null);
	}

	/**
	 * Set value of Operator
	 * @param operator
	 */
	public final databasereplication.proxies.Operator getOperator()
	{
		return getOperator(getContext());
	}

	/**
	 * @param context
	 * @return value of Operator
	 */
	public final databasereplication.proxies.Operator getOperator(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Operator.toString());
		if (obj == null)
			return null;

		return databasereplication.proxies.Operator.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Operator
	 * @param operator
	 */
	public final void setOperator(databasereplication.proxies.Operator operator)
	{
		setOperator(getContext(), operator);
	}

	/**
	 * Set value of Operator
	 * @param context
	 * @param operator
	 */
	public final void setOperator(com.mendix.systemwideinterfaces.core.IContext context, databasereplication.proxies.Operator operator)
	{
		if (operator != null)
			getMendixObject().setValue(context, MemberNames.Operator.toString(), operator.toString());
		else
			getMendixObject().setValue(context, MemberNames.Operator.toString(), null);
	}

	/**
	 * @return value of Value
	 */
	public final String getValue()
	{
		return getValue(getContext());
	}

	/**
	 * @param context
	 * @return value of Value
	 */
	public final String getValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Value.toString());
	}

	/**
	 * Set value of Value
	 * @param value
	 */
	public final void setValue(String value)
	{
		setValue(getContext(), value);
	}

	/**
	 * Set value of Value
	 * @param context
	 * @param value
	 */
	public final void setValue(com.mendix.systemwideinterfaces.core.IContext context, String value)
	{
		getMendixObject().setValue(context, MemberNames.Value.toString(), value);
	}

	/**
	 * Set value of InputObject
	 * @param inputobject
	 */
	public final databasereplication.proxies.ContraintInputObject getInputObject()
	{
		return getInputObject(getContext());
	}

	/**
	 * @param context
	 * @return value of InputObject
	 */
	public final databasereplication.proxies.ContraintInputObject getInputObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.InputObject.toString());
		if (obj == null)
			return null;

		return databasereplication.proxies.ContraintInputObject.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of InputObject
	 * @param inputobject
	 */
	public final void setInputObject(databasereplication.proxies.ContraintInputObject inputobject)
	{
		setInputObject(getContext(), inputobject);
	}

	/**
	 * Set value of InputObject
	 * @param context
	 * @param inputobject
	 */
	public final void setInputObject(com.mendix.systemwideinterfaces.core.IContext context, databasereplication.proxies.ContraintInputObject inputobject)
	{
		if (inputobject != null)
			getMendixObject().setValue(context, MemberNames.InputObject.toString(), inputobject.toString());
		else
			getMendixObject().setValue(context, MemberNames.InputObject.toString(), null);
	}

	/**
	 * @return value of Description
	 */
	public final String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of Token
	 */
	public final String getToken()
	{
		return getToken(getContext());
	}

	/**
	 * @param context
	 * @return value of Token
	 */
	public final String getToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Token.toString());
	}

	/**
	 * Set value of Token
	 * @param token
	 */
	public final void setToken(String token)
	{
		setToken(getContext(), token);
	}

	/**
	 * Set value of Token
	 * @param context
	 * @param token
	 */
	public final void setToken(com.mendix.systemwideinterfaces.core.IContext context, String token)
	{
		getMendixObject().setValue(context, MemberNames.Token.toString(), token);
	}

	/**
	 * @return value of IgnoreWhenEmpty
	 */
	public final Boolean getIgnoreWhenEmpty()
	{
		return getIgnoreWhenEmpty(getContext());
	}

	/**
	 * @param context
	 * @return value of IgnoreWhenEmpty
	 */
	public final Boolean getIgnoreWhenEmpty(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.IgnoreWhenEmpty.toString());
	}

	/**
	 * Set value of IgnoreWhenEmpty
	 * @param ignorewhenempty
	 */
	public final void setIgnoreWhenEmpty(Boolean ignorewhenempty)
	{
		setIgnoreWhenEmpty(getContext(), ignorewhenempty);
	}

	/**
	 * Set value of IgnoreWhenEmpty
	 * @param context
	 * @param ignorewhenempty
	 */
	public final void setIgnoreWhenEmpty(com.mendix.systemwideinterfaces.core.IContext context, Boolean ignorewhenempty)
	{
		getMendixObject().setValue(context, MemberNames.IgnoreWhenEmpty.toString(), ignorewhenempty);
	}

	/**
	 * @return value of CustomConstraint_AdditionalJoins
	 */
	public final databasereplication.proxies.AdditionalJoins getCustomConstraint_AdditionalJoins() throws com.mendix.core.CoreException
	{
		return getCustomConstraint_AdditionalJoins(getContext());
	}

	/**
	 * @param context
	 * @return value of CustomConstraint_AdditionalJoins
	 */
	public final databasereplication.proxies.AdditionalJoins getCustomConstraint_AdditionalJoins(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		databasereplication.proxies.AdditionalJoins result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CustomConstraint_AdditionalJoins.toString());
		if (identifier != null)
			result = databasereplication.proxies.AdditionalJoins.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CustomConstraint_AdditionalJoins
	 * @param customconstraint_additionaljoins
	 */
	public final void setCustomConstraint_AdditionalJoins(databasereplication.proxies.AdditionalJoins customconstraint_additionaljoins)
	{
		setCustomConstraint_AdditionalJoins(getContext(), customconstraint_additionaljoins);
	}

	/**
	 * Set value of CustomConstraint_AdditionalJoins
	 * @param context
	 * @param customconstraint_additionaljoins
	 */
	public final void setCustomConstraint_AdditionalJoins(com.mendix.systemwideinterfaces.core.IContext context, databasereplication.proxies.AdditionalJoins customconstraint_additionaljoins)
	{
		if (customconstraint_additionaljoins == null)
			getMendixObject().setValue(context, MemberNames.CustomConstraint_AdditionalJoins.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CustomConstraint_AdditionalJoins.toString(), customconstraint_additionaljoins.getMendixObject().getId());
	}

	/**
	 * @return value of CustomConstraint_Column
	 */
	public final databasereplication.proxies.Column getCustomConstraint_Column() throws com.mendix.core.CoreException
	{
		return getCustomConstraint_Column(getContext());
	}

	/**
	 * @param context
	 * @return value of CustomConstraint_Column
	 */
	public final databasereplication.proxies.Column getCustomConstraint_Column(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		databasereplication.proxies.Column result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CustomConstraint_Column.toString());
		if (identifier != null)
			result = databasereplication.proxies.Column.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CustomConstraint_Column
	 * @param customconstraint_column
	 */
	public final void setCustomConstraint_Column(databasereplication.proxies.Column customconstraint_column)
	{
		setCustomConstraint_Column(getContext(), customconstraint_column);
	}

	/**
	 * Set value of CustomConstraint_Column
	 * @param context
	 * @param customconstraint_column
	 */
	public final void setCustomConstraint_Column(com.mendix.systemwideinterfaces.core.IContext context, databasereplication.proxies.Column customconstraint_column)
	{
		if (customconstraint_column == null)
			getMendixObject().setValue(context, MemberNames.CustomConstraint_Column.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CustomConstraint_Column.toString(), customconstraint_column.getMendixObject().getId());
	}

	/**
	 * @return value of CustomConstraint_ImportCall
	 */
	public final databasereplication.proxies.ImportCall getCustomConstraint_ImportCall() throws com.mendix.core.CoreException
	{
		return getCustomConstraint_ImportCall(getContext());
	}

	/**
	 * @param context
	 * @return value of CustomConstraint_ImportCall
	 */
	public final databasereplication.proxies.ImportCall getCustomConstraint_ImportCall(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		databasereplication.proxies.ImportCall result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CustomConstraint_ImportCall.toString());
		if (identifier != null)
			result = databasereplication.proxies.ImportCall.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CustomConstraint_ImportCall
	 * @param customconstraint_importcall
	 */
	public final void setCustomConstraint_ImportCall(databasereplication.proxies.ImportCall customconstraint_importcall)
	{
		setCustomConstraint_ImportCall(getContext(), customconstraint_importcall);
	}

	/**
	 * Set value of CustomConstraint_ImportCall
	 * @param context
	 * @param customconstraint_importcall
	 */
	public final void setCustomConstraint_ImportCall(com.mendix.systemwideinterfaces.core.IContext context, databasereplication.proxies.ImportCall customconstraint_importcall)
	{
		if (customconstraint_importcall == null)
			getMendixObject().setValue(context, MemberNames.CustomConstraint_ImportCall.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CustomConstraint_ImportCall.toString(), customconstraint_importcall.getMendixObject().getId());
	}

	/**
	 * @return value of CustomConstraint_ColumnTemp
	 */
	public final databasereplication.proxies.ColumnTemp getCustomConstraint_ColumnTemp() throws com.mendix.core.CoreException
	{
		return getCustomConstraint_ColumnTemp(getContext());
	}

	/**
	 * @param context
	 * @return value of CustomConstraint_ColumnTemp
	 */
	public final databasereplication.proxies.ColumnTemp getCustomConstraint_ColumnTemp(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		databasereplication.proxies.ColumnTemp result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CustomConstraint_ColumnTemp.toString());
		if (identifier != null)
			result = databasereplication.proxies.ColumnTemp.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CustomConstraint_ColumnTemp
	 * @param customconstraint_columntemp
	 */
	public final void setCustomConstraint_ColumnTemp(databasereplication.proxies.ColumnTemp customconstraint_columntemp)
	{
		setCustomConstraint_ColumnTemp(getContext(), customconstraint_columntemp);
	}

	/**
	 * Set value of CustomConstraint_ColumnTemp
	 * @param context
	 * @param customconstraint_columntemp
	 */
	public final void setCustomConstraint_ColumnTemp(com.mendix.systemwideinterfaces.core.IContext context, databasereplication.proxies.ColumnTemp customconstraint_columntemp)
	{
		if (customconstraint_columntemp == null)
			getMendixObject().setValue(context, MemberNames.CustomConstraint_ColumnTemp.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CustomConstraint_ColumnTemp.toString(), customconstraint_columntemp.getMendixObject().getId());
	}

	/**
	 * @return value of CustomConstraint_AdditionalJoinTemp
	 */
	public final databasereplication.proxies.AdditionalJoinTemp getCustomConstraint_AdditionalJoinTemp() throws com.mendix.core.CoreException
	{
		return getCustomConstraint_AdditionalJoinTemp(getContext());
	}

	/**
	 * @param context
	 * @return value of CustomConstraint_AdditionalJoinTemp
	 */
	public final databasereplication.proxies.AdditionalJoinTemp getCustomConstraint_AdditionalJoinTemp(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		databasereplication.proxies.AdditionalJoinTemp result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CustomConstraint_AdditionalJoinTemp.toString());
		if (identifier != null)
			result = databasereplication.proxies.AdditionalJoinTemp.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CustomConstraint_AdditionalJoinTemp
	 * @param customconstraint_additionaljointemp
	 */
	public final void setCustomConstraint_AdditionalJoinTemp(databasereplication.proxies.AdditionalJoinTemp customconstraint_additionaljointemp)
	{
		setCustomConstraint_AdditionalJoinTemp(getContext(), customconstraint_additionaljointemp);
	}

	/**
	 * Set value of CustomConstraint_AdditionalJoinTemp
	 * @param context
	 * @param customconstraint_additionaljointemp
	 */
	public final void setCustomConstraint_AdditionalJoinTemp(com.mendix.systemwideinterfaces.core.IContext context, databasereplication.proxies.AdditionalJoinTemp customconstraint_additionaljointemp)
	{
		if (customconstraint_additionaljointemp == null)
			getMendixObject().setValue(context, MemberNames.CustomConstraint_AdditionalJoinTemp.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CustomConstraint_AdditionalJoinTemp.toString(), customconstraint_additionaljointemp.getMendixObject().getId());
	}

	/**
	 * @return value of CustomConstraint_MxObjectMember
	 */
	public final mxmodelreflection.proxies.MxObjectMember getCustomConstraint_MxObjectMember() throws com.mendix.core.CoreException
	{
		return getCustomConstraint_MxObjectMember(getContext());
	}

	/**
	 * @param context
	 * @return value of CustomConstraint_MxObjectMember
	 */
	public final mxmodelreflection.proxies.MxObjectMember getCustomConstraint_MxObjectMember(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxmodelreflection.proxies.MxObjectMember result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CustomConstraint_MxObjectMember.toString());
		if (identifier != null)
			result = mxmodelreflection.proxies.MxObjectMember.load(context, identifier);
		return result;
	}

	/**
	 * Set value of CustomConstraint_MxObjectMember
	 * @param customconstraint_mxobjectmember
	 */
	public final void setCustomConstraint_MxObjectMember(mxmodelreflection.proxies.MxObjectMember customconstraint_mxobjectmember)
	{
		setCustomConstraint_MxObjectMember(getContext(), customconstraint_mxobjectmember);
	}

	/**
	 * Set value of CustomConstraint_MxObjectMember
	 * @param context
	 * @param customconstraint_mxobjectmember
	 */
	public final void setCustomConstraint_MxObjectMember(com.mendix.systemwideinterfaces.core.IContext context, mxmodelreflection.proxies.MxObjectMember customconstraint_mxobjectmember)
	{
		if (customconstraint_mxobjectmember == null)
			getMendixObject().setValue(context, MemberNames.CustomConstraint_MxObjectMember.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.CustomConstraint_MxObjectMember.toString(), customconstraint_mxobjectmember.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return customConstraintMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final databasereplication.proxies.CustomConstraint that = (databasereplication.proxies.CustomConstraint) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DatabaseReplication.CustomConstraint";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
