// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databasereplication.proxies;

public class CustomConnectionInfo
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject customConnectionInfoMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DatabaseReplication.CustomConnectionInfo";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ConnectionString("ConnectionString"),
		DriverClass("DriverClass"),
		EscapeCharacterOpen("EscapeCharacterOpen"),
		EscapeCharacterClose("EscapeCharacterClose"),
		EscapeColumnNames("EscapeColumnNames"),
		EscapeTableNames("EscapeTableNames"),
		EscapeColumnAlias("EscapeColumnAlias"),
		EscapeTableAlias("EscapeTableAlias"),
		AllowsASToken("AllowsASToken"),
		SeparateEscapeSchemaTableName("SeparateEscapeSchemaTableName"),
		Example("Example"),
		Database_CustomConnectionInfo("DatabaseReplication.Database_CustomConnectionInfo");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CustomConnectionInfo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DatabaseReplication.CustomConnectionInfo"));
	}

	protected CustomConnectionInfo(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject customConnectionInfoMendixObject)
	{
		if (customConnectionInfoMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DatabaseReplication.CustomConnectionInfo", customConnectionInfoMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DatabaseReplication.CustomConnectionInfo");

		this.customConnectionInfoMendixObject = customConnectionInfoMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'CustomConnectionInfo.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static databasereplication.proxies.CustomConnectionInfo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return databasereplication.proxies.CustomConnectionInfo.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static databasereplication.proxies.CustomConnectionInfo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new databasereplication.proxies.CustomConnectionInfo(context, mendixObject);
	}

	public static databasereplication.proxies.CustomConnectionInfo load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return databasereplication.proxies.CustomConnectionInfo.initialize(context, mendixObject);
	}

	public static java.util.List<databasereplication.proxies.CustomConnectionInfo> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<databasereplication.proxies.CustomConnectionInfo> result = new java.util.ArrayList<databasereplication.proxies.CustomConnectionInfo>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DatabaseReplication.CustomConnectionInfo" + xpathConstraint))
			result.add(databasereplication.proxies.CustomConnectionInfo.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ConnectionString
	 */
	public final String getConnectionString()
	{
		return getConnectionString(getContext());
	}

	/**
	 * @param context
	 * @return value of ConnectionString
	 */
	public final String getConnectionString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.ConnectionString.toString());
	}

	/**
	 * Set value of ConnectionString
	 * @param connectionstring
	 */
	public final void setConnectionString(String connectionstring)
	{
		setConnectionString(getContext(), connectionstring);
	}

	/**
	 * Set value of ConnectionString
	 * @param context
	 * @param connectionstring
	 */
	public final void setConnectionString(com.mendix.systemwideinterfaces.core.IContext context, String connectionstring)
	{
		getMendixObject().setValue(context, MemberNames.ConnectionString.toString(), connectionstring);
	}

	/**
	 * @return value of DriverClass
	 */
	public final String getDriverClass()
	{
		return getDriverClass(getContext());
	}

	/**
	 * @param context
	 * @return value of DriverClass
	 */
	public final String getDriverClass(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.DriverClass.toString());
	}

	/**
	 * Set value of DriverClass
	 * @param driverclass
	 */
	public final void setDriverClass(String driverclass)
	{
		setDriverClass(getContext(), driverclass);
	}

	/**
	 * Set value of DriverClass
	 * @param context
	 * @param driverclass
	 */
	public final void setDriverClass(com.mendix.systemwideinterfaces.core.IContext context, String driverclass)
	{
		getMendixObject().setValue(context, MemberNames.DriverClass.toString(), driverclass);
	}

	/**
	 * @return value of EscapeCharacterOpen
	 */
	public final String getEscapeCharacterOpen()
	{
		return getEscapeCharacterOpen(getContext());
	}

	/**
	 * @param context
	 * @return value of EscapeCharacterOpen
	 */
	public final String getEscapeCharacterOpen(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.EscapeCharacterOpen.toString());
	}

	/**
	 * Set value of EscapeCharacterOpen
	 * @param escapecharacteropen
	 */
	public final void setEscapeCharacterOpen(String escapecharacteropen)
	{
		setEscapeCharacterOpen(getContext(), escapecharacteropen);
	}

	/**
	 * Set value of EscapeCharacterOpen
	 * @param context
	 * @param escapecharacteropen
	 */
	public final void setEscapeCharacterOpen(com.mendix.systemwideinterfaces.core.IContext context, String escapecharacteropen)
	{
		getMendixObject().setValue(context, MemberNames.EscapeCharacterOpen.toString(), escapecharacteropen);
	}

	/**
	 * @return value of EscapeCharacterClose
	 */
	public final String getEscapeCharacterClose()
	{
		return getEscapeCharacterClose(getContext());
	}

	/**
	 * @param context
	 * @return value of EscapeCharacterClose
	 */
	public final String getEscapeCharacterClose(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.EscapeCharacterClose.toString());
	}

	/**
	 * Set value of EscapeCharacterClose
	 * @param escapecharacterclose
	 */
	public final void setEscapeCharacterClose(String escapecharacterclose)
	{
		setEscapeCharacterClose(getContext(), escapecharacterclose);
	}

	/**
	 * Set value of EscapeCharacterClose
	 * @param context
	 * @param escapecharacterclose
	 */
	public final void setEscapeCharacterClose(com.mendix.systemwideinterfaces.core.IContext context, String escapecharacterclose)
	{
		getMendixObject().setValue(context, MemberNames.EscapeCharacterClose.toString(), escapecharacterclose);
	}

	/**
	 * @return value of EscapeColumnNames
	 */
	public final Boolean getEscapeColumnNames()
	{
		return getEscapeColumnNames(getContext());
	}

	/**
	 * @param context
	 * @return value of EscapeColumnNames
	 */
	public final Boolean getEscapeColumnNames(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.EscapeColumnNames.toString());
	}

	/**
	 * Set value of EscapeColumnNames
	 * @param escapecolumnnames
	 */
	public final void setEscapeColumnNames(Boolean escapecolumnnames)
	{
		setEscapeColumnNames(getContext(), escapecolumnnames);
	}

	/**
	 * Set value of EscapeColumnNames
	 * @param context
	 * @param escapecolumnnames
	 */
	public final void setEscapeColumnNames(com.mendix.systemwideinterfaces.core.IContext context, Boolean escapecolumnnames)
	{
		getMendixObject().setValue(context, MemberNames.EscapeColumnNames.toString(), escapecolumnnames);
	}

	/**
	 * @return value of EscapeTableNames
	 */
	public final Boolean getEscapeTableNames()
	{
		return getEscapeTableNames(getContext());
	}

	/**
	 * @param context
	 * @return value of EscapeTableNames
	 */
	public final Boolean getEscapeTableNames(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.EscapeTableNames.toString());
	}

	/**
	 * Set value of EscapeTableNames
	 * @param escapetablenames
	 */
	public final void setEscapeTableNames(Boolean escapetablenames)
	{
		setEscapeTableNames(getContext(), escapetablenames);
	}

	/**
	 * Set value of EscapeTableNames
	 * @param context
	 * @param escapetablenames
	 */
	public final void setEscapeTableNames(com.mendix.systemwideinterfaces.core.IContext context, Boolean escapetablenames)
	{
		getMendixObject().setValue(context, MemberNames.EscapeTableNames.toString(), escapetablenames);
	}

	/**
	 * @return value of EscapeColumnAlias
	 */
	public final Boolean getEscapeColumnAlias()
	{
		return getEscapeColumnAlias(getContext());
	}

	/**
	 * @param context
	 * @return value of EscapeColumnAlias
	 */
	public final Boolean getEscapeColumnAlias(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.EscapeColumnAlias.toString());
	}

	/**
	 * Set value of EscapeColumnAlias
	 * @param escapecolumnalias
	 */
	public final void setEscapeColumnAlias(Boolean escapecolumnalias)
	{
		setEscapeColumnAlias(getContext(), escapecolumnalias);
	}

	/**
	 * Set value of EscapeColumnAlias
	 * @param context
	 * @param escapecolumnalias
	 */
	public final void setEscapeColumnAlias(com.mendix.systemwideinterfaces.core.IContext context, Boolean escapecolumnalias)
	{
		getMendixObject().setValue(context, MemberNames.EscapeColumnAlias.toString(), escapecolumnalias);
	}

	/**
	 * @return value of EscapeTableAlias
	 */
	public final Boolean getEscapeTableAlias()
	{
		return getEscapeTableAlias(getContext());
	}

	/**
	 * @param context
	 * @return value of EscapeTableAlias
	 */
	public final Boolean getEscapeTableAlias(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.EscapeTableAlias.toString());
	}

	/**
	 * Set value of EscapeTableAlias
	 * @param escapetablealias
	 */
	public final void setEscapeTableAlias(Boolean escapetablealias)
	{
		setEscapeTableAlias(getContext(), escapetablealias);
	}

	/**
	 * Set value of EscapeTableAlias
	 * @param context
	 * @param escapetablealias
	 */
	public final void setEscapeTableAlias(com.mendix.systemwideinterfaces.core.IContext context, Boolean escapetablealias)
	{
		getMendixObject().setValue(context, MemberNames.EscapeTableAlias.toString(), escapetablealias);
	}

	/**
	 * @return value of AllowsASToken
	 */
	public final Boolean getAllowsASToken()
	{
		return getAllowsASToken(getContext());
	}

	/**
	 * @param context
	 * @return value of AllowsASToken
	 */
	public final Boolean getAllowsASToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.AllowsASToken.toString());
	}

	/**
	 * Set value of AllowsASToken
	 * @param allowsastoken
	 */
	public final void setAllowsASToken(Boolean allowsastoken)
	{
		setAllowsASToken(getContext(), allowsastoken);
	}

	/**
	 * Set value of AllowsASToken
	 * @param context
	 * @param allowsastoken
	 */
	public final void setAllowsASToken(com.mendix.systemwideinterfaces.core.IContext context, Boolean allowsastoken)
	{
		getMendixObject().setValue(context, MemberNames.AllowsASToken.toString(), allowsastoken);
	}

	/**
	 * @return value of SeparateEscapeSchemaTableName
	 */
	public final Boolean getSeparateEscapeSchemaTableName()
	{
		return getSeparateEscapeSchemaTableName(getContext());
	}

	/**
	 * @param context
	 * @return value of SeparateEscapeSchemaTableName
	 */
	public final Boolean getSeparateEscapeSchemaTableName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.SeparateEscapeSchemaTableName.toString());
	}

	/**
	 * Set value of SeparateEscapeSchemaTableName
	 * @param separateescapeschematablename
	 */
	public final void setSeparateEscapeSchemaTableName(Boolean separateescapeschematablename)
	{
		setSeparateEscapeSchemaTableName(getContext(), separateescapeschematablename);
	}

	/**
	 * Set value of SeparateEscapeSchemaTableName
	 * @param context
	 * @param separateescapeschematablename
	 */
	public final void setSeparateEscapeSchemaTableName(com.mendix.systemwideinterfaces.core.IContext context, Boolean separateescapeschematablename)
	{
		getMendixObject().setValue(context, MemberNames.SeparateEscapeSchemaTableName.toString(), separateescapeschematablename);
	}

	/**
	 * @return value of Example
	 */
	public final String getExample()
	{
		return getExample(getContext());
	}

	/**
	 * @param context
	 * @return value of Example
	 */
	public final String getExample(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Example.toString());
	}

	/**
	 * Set value of Example
	 * @param example
	 */
	public final void setExample(String example)
	{
		setExample(getContext(), example);
	}

	/**
	 * Set value of Example
	 * @param context
	 * @param example
	 */
	public final void setExample(com.mendix.systemwideinterfaces.core.IContext context, String example)
	{
		getMendixObject().setValue(context, MemberNames.Example.toString(), example);
	}

	/**
	 * @return value of Database_CustomConnectionInfo
	 */
	public final databasereplication.proxies.Database getDatabase_CustomConnectionInfo() throws com.mendix.core.CoreException
	{
		return getDatabase_CustomConnectionInfo(getContext());
	}

	/**
	 * @param context
	 * @return value of Database_CustomConnectionInfo
	 */
	public final databasereplication.proxies.Database getDatabase_CustomConnectionInfo(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		databasereplication.proxies.Database result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Database_CustomConnectionInfo.toString());
		if (identifier != null)
			result = databasereplication.proxies.Database.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Database_CustomConnectionInfo
	 * @param database_customconnectioninfo
	 */
	public final void setDatabase_CustomConnectionInfo(databasereplication.proxies.Database database_customconnectioninfo)
	{
		setDatabase_CustomConnectionInfo(getContext(), database_customconnectioninfo);
	}

	/**
	 * Set value of Database_CustomConnectionInfo
	 * @param context
	 * @param database_customconnectioninfo
	 */
	public final void setDatabase_CustomConnectionInfo(com.mendix.systemwideinterfaces.core.IContext context, databasereplication.proxies.Database database_customconnectioninfo)
	{
		if (database_customconnectioninfo == null)
			getMendixObject().setValue(context, MemberNames.Database_CustomConnectionInfo.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Database_CustomConnectionInfo.toString(), database_customconnectioninfo.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return customConnectionInfoMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final databasereplication.proxies.CustomConnectionInfo that = (databasereplication.proxies.CustomConnectionInfo) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DatabaseReplication.CustomConnectionInfo";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
