// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databasereplication.proxies;

public enum DBType
{
	SQLServer2005(new String[][] { new String[] { "en_US", "MS SQLServer 2005" }, new String[] { "nl_NL", "MS SQLServer 2005" }, new String[] { "en_GB", "MS SQLServer 2005" }, new String[] { "en_ZA", "MS SQLServer 2005" } }),
	SQLServer2008(new String[][] { new String[] { "en_US", "MS SQLServer 2008" }, new String[] { "nl_NL", "MS SQLServer 2008" }, new String[] { "en_GB", "MS SQLServer 2008" }, new String[] { "en_ZA", "MS SQLServer 2008" } }),
	Oracle(new String[][] { new String[] { "en_US", "Oracle" }, new String[] { "nl_NL", "Oracle" }, new String[] { "en_GB", "Oracle" }, new String[] { "en_ZA", "Oracle" } }),
	Postgres(new String[][] { new String[] { "en_US", "PostgreSQL" }, new String[] { "nl_NL", "PostgreSQL" }, new String[] { "en_GB", "PostgreSQL" }, new String[] { "en_ZA", "PostgreSQL" } }),
	AS_400(new String[][] { new String[] { "en_US", "AS/400 - DB2" }, new String[] { "nl_NL", "AS/400 - DB2" }, new String[] { "en_GB", "AS/400 - DB2" }, new String[] { "en_ZA", "AS/400 - DB2" } }),
	Custom(new String[][] { new String[] { "en_US", "Custom" }, new String[] { "nl_NL", "Custom" }, new String[] { "en_GB", "Custom" }, new String[] { "en_ZA", "Custom" } }),
	Informix(new String[][] { new String[] { "en_US", "Informix" }, new String[] { "nl_NL", "Informix" }, new String[] { "en_GB", "Informix" }, new String[] { "en_ZA", "Informix" } }),
	DMS2(new String[][] { new String[] { "en_US", "DMS2" }, new String[] { "nl_NL", "DMS2" }, new String[] { "en_GB", "DMS2" }, new String[] { "en_ZA", "DMS2" } }),
	MSAccess(new String[][] { new String[] { "en_US", "MSAccess" }, new String[] { "en_GB", "MSAccess" }, new String[] { "en_ZA", "MSAccess" }, new String[] { "nl_NL", "MS Access" } });

	private java.util.Map<String,String> captions;

	private DBType(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
