// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databasereplication.proxies;

public class ImportCall
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject importCallMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DatabaseReplication.ImportCall";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ConstraintDependency("ConstraintDependency"),
		ImportTable("ImportTable"),
		ConstraintMode("ConstraintMode"),
		RefNr("RefNr"),
		ImportRefNr("ImportRefNr"),
		SetReferenceToEntityOne("SetReferenceToEntityOne"),
		SetReferenceToEntityTwo("SetReferenceToEntityTwo"),
		ImportCall_TableMapping("DatabaseReplication.ImportCall_TableMapping"),
		ImportCallOne_MxObjectType("DatabaseReplication.ImportCallOne_MxObjectType"),
		ImportCalTwo_MxObjectType("DatabaseReplication.ImportCalTwo_MxObjectType"),
		ImportCallOne_MxObjectReference("DatabaseReplication.ImportCallOne_MxObjectReference"),
		ImportCallTwo_MxObjectReference("DatabaseReplication.ImportCallTwo_MxObjectReference");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ImportCall(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DatabaseReplication.ImportCall"));
	}

	protected ImportCall(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject importCallMendixObject)
	{
		if (importCallMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DatabaseReplication.ImportCall", importCallMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DatabaseReplication.ImportCall");

		this.importCallMendixObject = importCallMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ImportCall.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static databasereplication.proxies.ImportCall initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return databasereplication.proxies.ImportCall.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static databasereplication.proxies.ImportCall initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new databasereplication.proxies.ImportCall(context, mendixObject);
	}

	public static databasereplication.proxies.ImportCall load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return databasereplication.proxies.ImportCall.initialize(context, mendixObject);
	}

	public static java.util.List<databasereplication.proxies.ImportCall> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<databasereplication.proxies.ImportCall> result = new java.util.ArrayList<databasereplication.proxies.ImportCall>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DatabaseReplication.ImportCall" + xpathConstraint))
			result.add(databasereplication.proxies.ImportCall.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ConstraintDependency
	 */
	public final String getConstraintDependency()
	{
		return getConstraintDependency(getContext());
	}

	/**
	 * @param context
	 * @return value of ConstraintDependency
	 */
	public final String getConstraintDependency(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.ConstraintDependency.toString());
	}

	/**
	 * Set value of ConstraintDependency
	 * @param constraintdependency
	 */
	public final void setConstraintDependency(String constraintdependency)
	{
		setConstraintDependency(getContext(), constraintdependency);
	}

	/**
	 * Set value of ConstraintDependency
	 * @param context
	 * @param constraintdependency
	 */
	public final void setConstraintDependency(com.mendix.systemwideinterfaces.core.IContext context, String constraintdependency)
	{
		getMendixObject().setValue(context, MemberNames.ConstraintDependency.toString(), constraintdependency);
	}

	/**
	 * @return value of ImportTable
	 */
	public final String getImportTable()
	{
		return getImportTable(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportTable
	 */
	public final String getImportTable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.ImportTable.toString());
	}

	/**
	 * Set value of ImportTable
	 * @param importtable
	 */
	public final void setImportTable(String importtable)
	{
		setImportTable(getContext(), importtable);
	}

	/**
	 * Set value of ImportTable
	 * @param context
	 * @param importtable
	 */
	public final void setImportTable(com.mendix.systemwideinterfaces.core.IContext context, String importtable)
	{
		getMendixObject().setValue(context, MemberNames.ImportTable.toString(), importtable);
	}

	/**
	 * Set value of ConstraintMode
	 * @param constraintmode
	 */
	public final databasereplication.proxies.Mode getConstraintMode()
	{
		return getConstraintMode(getContext());
	}

	/**
	 * @param context
	 * @return value of ConstraintMode
	 */
	public final databasereplication.proxies.Mode getConstraintMode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ConstraintMode.toString());
		if (obj == null)
			return null;

		return databasereplication.proxies.Mode.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ConstraintMode
	 * @param constraintmode
	 */
	public final void setConstraintMode(databasereplication.proxies.Mode constraintmode)
	{
		setConstraintMode(getContext(), constraintmode);
	}

	/**
	 * Set value of ConstraintMode
	 * @param context
	 * @param constraintmode
	 */
	public final void setConstraintMode(com.mendix.systemwideinterfaces.core.IContext context, databasereplication.proxies.Mode constraintmode)
	{
		if (constraintmode != null)
			getMendixObject().setValue(context, MemberNames.ConstraintMode.toString(), constraintmode.toString());
		else
			getMendixObject().setValue(context, MemberNames.ConstraintMode.toString(), null);
	}

	/**
	 * @return value of RefNr
	 */
	public final Long getRefNr()
	{
		return getRefNr(getContext());
	}

	/**
	 * @param context
	 * @return value of RefNr
	 */
	public final Long getRefNr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Long) getMendixObject().getValue(context, MemberNames.RefNr.toString());
	}

	/**
	 * Set value of RefNr
	 * @param refnr
	 */
	public final void setRefNr(Long refnr)
	{
		setRefNr(getContext(), refnr);
	}

	/**
	 * Set value of RefNr
	 * @param context
	 * @param refnr
	 */
	public final void setRefNr(com.mendix.systemwideinterfaces.core.IContext context, Long refnr)
	{
		getMendixObject().setValue(context, MemberNames.RefNr.toString(), refnr);
	}

	/**
	 * @return value of ImportRefNr
	 */
	public final Long getImportRefNr()
	{
		return getImportRefNr(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportRefNr
	 */
	public final Long getImportRefNr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Long) getMendixObject().getValue(context, MemberNames.ImportRefNr.toString());
	}

	/**
	 * Set value of ImportRefNr
	 * @param importrefnr
	 */
	public final void setImportRefNr(Long importrefnr)
	{
		setImportRefNr(getContext(), importrefnr);
	}

	/**
	 * Set value of ImportRefNr
	 * @param context
	 * @param importrefnr
	 */
	public final void setImportRefNr(com.mendix.systemwideinterfaces.core.IContext context, Long importrefnr)
	{
		getMendixObject().setValue(context, MemberNames.ImportRefNr.toString(), importrefnr);
	}

	/**
	 * @return value of SetReferenceToEntityOne
	 */
	public final Boolean getSetReferenceToEntityOne()
	{
		return getSetReferenceToEntityOne(getContext());
	}

	/**
	 * @param context
	 * @return value of SetReferenceToEntityOne
	 */
	public final Boolean getSetReferenceToEntityOne(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.SetReferenceToEntityOne.toString());
	}

	/**
	 * Set value of SetReferenceToEntityOne
	 * @param setreferencetoentityone
	 */
	public final void setSetReferenceToEntityOne(Boolean setreferencetoentityone)
	{
		setSetReferenceToEntityOne(getContext(), setreferencetoentityone);
	}

	/**
	 * Set value of SetReferenceToEntityOne
	 * @param context
	 * @param setreferencetoentityone
	 */
	public final void setSetReferenceToEntityOne(com.mendix.systemwideinterfaces.core.IContext context, Boolean setreferencetoentityone)
	{
		getMendixObject().setValue(context, MemberNames.SetReferenceToEntityOne.toString(), setreferencetoentityone);
	}

	/**
	 * @return value of SetReferenceToEntityTwo
	 */
	public final Boolean getSetReferenceToEntityTwo()
	{
		return getSetReferenceToEntityTwo(getContext());
	}

	/**
	 * @param context
	 * @return value of SetReferenceToEntityTwo
	 */
	public final Boolean getSetReferenceToEntityTwo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.SetReferenceToEntityTwo.toString());
	}

	/**
	 * Set value of SetReferenceToEntityTwo
	 * @param setreferencetoentitytwo
	 */
	public final void setSetReferenceToEntityTwo(Boolean setreferencetoentitytwo)
	{
		setSetReferenceToEntityTwo(getContext(), setreferencetoentitytwo);
	}

	/**
	 * Set value of SetReferenceToEntityTwo
	 * @param context
	 * @param setreferencetoentitytwo
	 */
	public final void setSetReferenceToEntityTwo(com.mendix.systemwideinterfaces.core.IContext context, Boolean setreferencetoentitytwo)
	{
		getMendixObject().setValue(context, MemberNames.SetReferenceToEntityTwo.toString(), setreferencetoentitytwo);
	}

	/**
	 * @return value of ImportCall_TableMapping
	 */
	public final databasereplication.proxies.TableMapping getImportCall_TableMapping() throws com.mendix.core.CoreException
	{
		return getImportCall_TableMapping(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportCall_TableMapping
	 */
	public final databasereplication.proxies.TableMapping getImportCall_TableMapping(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		databasereplication.proxies.TableMapping result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ImportCall_TableMapping.toString());
		if (identifier != null)
			result = databasereplication.proxies.TableMapping.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ImportCall_TableMapping
	 * @param importcall_tablemapping
	 */
	public final void setImportCall_TableMapping(databasereplication.proxies.TableMapping importcall_tablemapping)
	{
		setImportCall_TableMapping(getContext(), importcall_tablemapping);
	}

	/**
	 * Set value of ImportCall_TableMapping
	 * @param context
	 * @param importcall_tablemapping
	 */
	public final void setImportCall_TableMapping(com.mendix.systemwideinterfaces.core.IContext context, databasereplication.proxies.TableMapping importcall_tablemapping)
	{
		if (importcall_tablemapping == null)
			getMendixObject().setValue(context, MemberNames.ImportCall_TableMapping.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ImportCall_TableMapping.toString(), importcall_tablemapping.getMendixObject().getId());
	}

	/**
	 * @return value of ImportCallOne_MxObjectType
	 */
	public final mxmodelreflection.proxies.MxObjectType getImportCallOne_MxObjectType() throws com.mendix.core.CoreException
	{
		return getImportCallOne_MxObjectType(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportCallOne_MxObjectType
	 */
	public final mxmodelreflection.proxies.MxObjectType getImportCallOne_MxObjectType(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxmodelreflection.proxies.MxObjectType result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ImportCallOne_MxObjectType.toString());
		if (identifier != null)
			result = mxmodelreflection.proxies.MxObjectType.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ImportCallOne_MxObjectType
	 * @param importcallone_mxobjecttype
	 */
	public final void setImportCallOne_MxObjectType(mxmodelreflection.proxies.MxObjectType importcallone_mxobjecttype)
	{
		setImportCallOne_MxObjectType(getContext(), importcallone_mxobjecttype);
	}

	/**
	 * Set value of ImportCallOne_MxObjectType
	 * @param context
	 * @param importcallone_mxobjecttype
	 */
	public final void setImportCallOne_MxObjectType(com.mendix.systemwideinterfaces.core.IContext context, mxmodelreflection.proxies.MxObjectType importcallone_mxobjecttype)
	{
		if (importcallone_mxobjecttype == null)
			getMendixObject().setValue(context, MemberNames.ImportCallOne_MxObjectType.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ImportCallOne_MxObjectType.toString(), importcallone_mxobjecttype.getMendixObject().getId());
	}

	/**
	 * @return value of ImportCalTwo_MxObjectType
	 */
	public final mxmodelreflection.proxies.MxObjectType getImportCalTwo_MxObjectType() throws com.mendix.core.CoreException
	{
		return getImportCalTwo_MxObjectType(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportCalTwo_MxObjectType
	 */
	public final mxmodelreflection.proxies.MxObjectType getImportCalTwo_MxObjectType(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxmodelreflection.proxies.MxObjectType result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ImportCalTwo_MxObjectType.toString());
		if (identifier != null)
			result = mxmodelreflection.proxies.MxObjectType.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ImportCalTwo_MxObjectType
	 * @param importcaltwo_mxobjecttype
	 */
	public final void setImportCalTwo_MxObjectType(mxmodelreflection.proxies.MxObjectType importcaltwo_mxobjecttype)
	{
		setImportCalTwo_MxObjectType(getContext(), importcaltwo_mxobjecttype);
	}

	/**
	 * Set value of ImportCalTwo_MxObjectType
	 * @param context
	 * @param importcaltwo_mxobjecttype
	 */
	public final void setImportCalTwo_MxObjectType(com.mendix.systemwideinterfaces.core.IContext context, mxmodelreflection.proxies.MxObjectType importcaltwo_mxobjecttype)
	{
		if (importcaltwo_mxobjecttype == null)
			getMendixObject().setValue(context, MemberNames.ImportCalTwo_MxObjectType.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ImportCalTwo_MxObjectType.toString(), importcaltwo_mxobjecttype.getMendixObject().getId());
	}

	/**
	 * @return value of ImportCallOne_MxObjectReference
	 */
	public final mxmodelreflection.proxies.MxObjectReference getImportCallOne_MxObjectReference() throws com.mendix.core.CoreException
	{
		return getImportCallOne_MxObjectReference(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportCallOne_MxObjectReference
	 */
	public final mxmodelreflection.proxies.MxObjectReference getImportCallOne_MxObjectReference(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxmodelreflection.proxies.MxObjectReference result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ImportCallOne_MxObjectReference.toString());
		if (identifier != null)
			result = mxmodelreflection.proxies.MxObjectReference.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ImportCallOne_MxObjectReference
	 * @param importcallone_mxobjectreference
	 */
	public final void setImportCallOne_MxObjectReference(mxmodelreflection.proxies.MxObjectReference importcallone_mxobjectreference)
	{
		setImportCallOne_MxObjectReference(getContext(), importcallone_mxobjectreference);
	}

	/**
	 * Set value of ImportCallOne_MxObjectReference
	 * @param context
	 * @param importcallone_mxobjectreference
	 */
	public final void setImportCallOne_MxObjectReference(com.mendix.systemwideinterfaces.core.IContext context, mxmodelreflection.proxies.MxObjectReference importcallone_mxobjectreference)
	{
		if (importcallone_mxobjectreference == null)
			getMendixObject().setValue(context, MemberNames.ImportCallOne_MxObjectReference.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ImportCallOne_MxObjectReference.toString(), importcallone_mxobjectreference.getMendixObject().getId());
	}

	/**
	 * @return value of ImportCallTwo_MxObjectReference
	 */
	public final mxmodelreflection.proxies.MxObjectReference getImportCallTwo_MxObjectReference() throws com.mendix.core.CoreException
	{
		return getImportCallTwo_MxObjectReference(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportCallTwo_MxObjectReference
	 */
	public final mxmodelreflection.proxies.MxObjectReference getImportCallTwo_MxObjectReference(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxmodelreflection.proxies.MxObjectReference result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ImportCallTwo_MxObjectReference.toString());
		if (identifier != null)
			result = mxmodelreflection.proxies.MxObjectReference.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ImportCallTwo_MxObjectReference
	 * @param importcalltwo_mxobjectreference
	 */
	public final void setImportCallTwo_MxObjectReference(mxmodelreflection.proxies.MxObjectReference importcalltwo_mxobjectreference)
	{
		setImportCallTwo_MxObjectReference(getContext(), importcalltwo_mxobjectreference);
	}

	/**
	 * Set value of ImportCallTwo_MxObjectReference
	 * @param context
	 * @param importcalltwo_mxobjectreference
	 */
	public final void setImportCallTwo_MxObjectReference(com.mendix.systemwideinterfaces.core.IContext context, mxmodelreflection.proxies.MxObjectReference importcalltwo_mxobjectreference)
	{
		if (importcalltwo_mxobjectreference == null)
			getMendixObject().setValue(context, MemberNames.ImportCallTwo_MxObjectReference.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ImportCallTwo_MxObjectReference.toString(), importcalltwo_mxobjectreference.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return importCallMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final databasereplication.proxies.ImportCall that = (databasereplication.proxies.ImportCall) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DatabaseReplication.ImportCall";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
