// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databasereplication.proxies;

public enum Operator
{
	Equal(new String[][] { new String[] { "en_US", "=" }, new String[] { "nl_NL", "=" }, new String[] { "en_GB", "=" }, new String[] { "en_ZA", "=" } }),
	Larger(new String[][] { new String[] { "en_US", ">" }, new String[] { "nl_NL", ">" }, new String[] { "en_GB", ">" }, new String[] { "en_ZA", ">" } }),
	LargerOrEqual(new String[][] { new String[] { "en_US", ">=" }, new String[] { "nl_NL", ">=" }, new String[] { "en_GB", ">=" }, new String[] { "en_ZA", ">=" } }),
	Smaller(new String[][] { new String[] { "en_US", "<" }, new String[] { "nl_NL", "<" }, new String[] { "en_GB", "<" }, new String[] { "en_ZA", "<" } }),
	SmallerOrEqual(new String[][] { new String[] { "en_US", "<=" }, new String[] { "nl_NL", "<=" }, new String[] { "en_GB", "<=" }, new String[] { "en_ZA", "<=" } }),
	NotEqual(new String[][] { new String[] { "en_US", "!=" }, new String[] { "nl_NL", "!=" }, new String[] { "en_GB", "!=" }, new String[] { "en_ZA", "!=" } }),
	Is_NULL(new String[][] { new String[] { "nl_NL", "Is NULL" }, new String[] { "en_US", "Is NULL" }, new String[] { "en_GB", "Is NULL" }, new String[] { "en_ZA", "Is NULL" } }),
	Is_not_NULL(new String[][] { new String[] { "nl_NL", "Is not NULL" }, new String[] { "en_US", "Is not NULL" }, new String[] { "en_GB", "Is not NULL" }, new String[] { "en_ZA", "Is not NULL" } }),
	LIKE(new String[][] { new String[] { "en_US", "LIKE" }, new String[] { "nl_NL", "Like" }, new String[] { "en_GB", "LIKE" }, new String[] { "en_ZA", "LIKE" } });

	private java.util.Map<String,String> captions;

	private Operator(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
