// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databasereplication.proxies;

public enum QueryType
{
	Automatic(new String[][] { new String[] { "en_US", "Automatic" }, new String[] { "nl_NL", "Automatisch" }, new String[] { "en_GB", "Automatic" }, new String[] { "en_ZA", "Automatic" } }),
	Custom(new String[][] { new String[] { "en_US", "Custom" }, new String[] { "nl_NL", "Custom" }, new String[] { "en_GB", "Custom" }, new String[] { "en_ZA", "Custom" } });

	private java.util.Map<String,String> captions;

	private QueryType(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
