// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databasereplication.proxies;

public enum ReferenceHandlingEnum
{
	FindCreate(new String[][] { new String[] { "en_US", "Find reference, create if not found" }, new String[] { "nl_NL", "Zoek referentie creeër wanneer niet gevonden" }, new String[] { "en_GB", "Find reference, create if not found" }, new String[] { "en_ZA", "Find reference, create if not found" } }),
	FindIgnore(new String[][] { new String[] { "en_US", "Find reference, ignore if not found" }, new String[] { "nl_NL", "Zoek referentie negeren wanneer niet gevonden" }, new String[] { "en_GB", "Find reference, ignore if not found" }, new String[] { "en_ZA", "Find reference, ignore if not found" } }),
	CreateEverything(new String[][] { new String[] { "en_US", "Create everything" }, new String[] { "nl_NL", "Maak alles aan" }, new String[] { "en_GB", "Create everything" }, new String[] { "en_ZA", "Create everything" } }),
	OnlyCreateNewObjects(new String[][] { new String[] { "en_US", "Only create new objects" }, new String[] { "nl_NL", "Maak alleen niet bestaande objecten" }, new String[] { "en_GB", "Only create new objects" }, new String[] { "en_ZA", "Only create new objects" } });

	private java.util.Map<String,String> captions;

	private ReferenceHandlingEnum(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
