// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databasereplication.proxies;

public enum ReplicationStatusValues
{
	Succesfull(new String[][] { new String[] { "nl_NL", "Succesvol" }, new String[] { "en_US", "Succesfull" }, new String[] { "en_GB", "Succesfull" }, new String[] { "en_ZA", "Succesfull" } }),
	Failed(new String[][] { new String[] { "nl_NL", "Mislukt" }, new String[] { "en_US", "Failed" }, new String[] { "en_GB", "Failed" }, new String[] { "en_ZA", "Failed" } }),
	FailedBeforeConnecting(new String[][] { new String[] { "nl_NL", "Mislukt voor verbinden" }, new String[] { "en_US", "Failed before connecting" }, new String[] { "en_GB", "Failed before connecting" }, new String[] { "en_ZA", "Failed before connecting" } });

	private java.util.Map<String,String> captions;

	private ReplicationStatusValues(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
