// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databasereplication.proxies;

public class TableFilter
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject tableFilterMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DatabaseReplication.TableFilter";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Filter("Filter"),
		TableFilter_Database("DatabaseReplication.TableFilter_Database");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TableFilter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DatabaseReplication.TableFilter"));
	}

	protected TableFilter(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject tableFilterMendixObject)
	{
		if (tableFilterMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DatabaseReplication.TableFilter", tableFilterMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DatabaseReplication.TableFilter");

		this.tableFilterMendixObject = tableFilterMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TableFilter.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static databasereplication.proxies.TableFilter initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return databasereplication.proxies.TableFilter.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static databasereplication.proxies.TableFilter initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new databasereplication.proxies.TableFilter(context, mendixObject);
	}

	public static databasereplication.proxies.TableFilter load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return databasereplication.proxies.TableFilter.initialize(context, mendixObject);
	}

	public static java.util.List<databasereplication.proxies.TableFilter> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<databasereplication.proxies.TableFilter> result = new java.util.ArrayList<databasereplication.proxies.TableFilter>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DatabaseReplication.TableFilter" + xpathConstraint))
			result.add(databasereplication.proxies.TableFilter.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Filter
	 */
	public final String getFilter()
	{
		return getFilter(getContext());
	}

	/**
	 * @param context
	 * @return value of Filter
	 */
	public final String getFilter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Filter.toString());
	}

	/**
	 * Set value of Filter
	 * @param filter
	 */
	public final void setFilter(String filter)
	{
		setFilter(getContext(), filter);
	}

	/**
	 * Set value of Filter
	 * @param context
	 * @param filter
	 */
	public final void setFilter(com.mendix.systemwideinterfaces.core.IContext context, String filter)
	{
		getMendixObject().setValue(context, MemberNames.Filter.toString(), filter);
	}

	/**
	 * @return value of TableFilter_Database
	 */
	public final databasereplication.proxies.Database getTableFilter_Database() throws com.mendix.core.CoreException
	{
		return getTableFilter_Database(getContext());
	}

	/**
	 * @param context
	 * @return value of TableFilter_Database
	 */
	public final databasereplication.proxies.Database getTableFilter_Database(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		databasereplication.proxies.Database result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TableFilter_Database.toString());
		if (identifier != null)
			result = databasereplication.proxies.Database.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TableFilter_Database
	 * @param tablefilter_database
	 */
	public final void setTableFilter_Database(databasereplication.proxies.Database tablefilter_database)
	{
		setTableFilter_Database(getContext(), tablefilter_database);
	}

	/**
	 * Set value of TableFilter_Database
	 * @param context
	 * @param tablefilter_database
	 */
	public final void setTableFilter_Database(com.mendix.systemwideinterfaces.core.IContext context, databasereplication.proxies.Database tablefilter_database)
	{
		if (tablefilter_database == null)
			getMendixObject().setValue(context, MemberNames.TableFilter_Database.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TableFilter_Database.toString(), tablefilter_database.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return tableFilterMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final databasereplication.proxies.TableFilter that = (databasereplication.proxies.TableFilter) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DatabaseReplication.TableFilter";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
