// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databasereplication.proxies;

public class TableMapping
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject tableMappingMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DatabaseReplication.TableMapping";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Number("Number"),
		RefNr("RefNr"),
		Description("Description"),
		Valid("Valid"),
		UseCustomConstraints("UseCustomConstraints"),
		SQLConstraint("SQLConstraint"),
		PrintStatisticsMessages("PrintStatisticsMessages"),
		RemoveUnsyncedObjects("RemoveUnsyncedObjects"),
		Mode("Mode"),
		UseTransactions("UseTransactions"),
		ImportInNewContext("ImportInNewContext"),
		IgnoreEmptyKeys("IgnoreEmptyKeys"),
		ImportAction("ImportAction"),
		ResetEmptyAssociations("ResetEmptyAssociations"),
		CommitUnchangedObjects_MainObject("CommitUnchangedObjects_MainObject"),
		PrintNotFoundMessages_MainObject("PrintNotFoundMessages_MainObject"),
		DatabaseType("DatabaseType"),
		TableMapping_Table("DatabaseReplication.TableMapping_Table"),
		TableMapping_Database("DatabaseReplication.TableMapping_Database"),
		TableMapping_XMLDocumentTM("DatabaseReplication.TableMapping_XMLDocumentTM"),
		TableMapping_MxObjectType("DatabaseReplication.TableMapping_MxObjectType"),
		TableMapping_MxObjectMember("DatabaseReplication.TableMapping_MxObjectMember"),
		TableMapping_Microflows("DatabaseReplication.TableMapping_Microflows");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TableMapping(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DatabaseReplication.TableMapping"));
	}

	protected TableMapping(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject tableMappingMendixObject)
	{
		if (tableMappingMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DatabaseReplication.TableMapping", tableMappingMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DatabaseReplication.TableMapping");

		this.tableMappingMendixObject = tableMappingMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TableMapping.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static databasereplication.proxies.TableMapping initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return databasereplication.proxies.TableMapping.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static databasereplication.proxies.TableMapping initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new databasereplication.proxies.TableMapping(context, mendixObject);
	}

	public static databasereplication.proxies.TableMapping load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return databasereplication.proxies.TableMapping.initialize(context, mendixObject);
	}

	public static java.util.List<databasereplication.proxies.TableMapping> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<databasereplication.proxies.TableMapping> result = new java.util.ArrayList<databasereplication.proxies.TableMapping>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DatabaseReplication.TableMapping" + xpathConstraint))
			result.add(databasereplication.proxies.TableMapping.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Number
	 */
	public final Long getNumber()
	{
		return getNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of Number
	 */
	public final Long getNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Long) getMendixObject().getValue(context, MemberNames.Number.toString());
	}

	/**
	 * Set value of Number
	 * @param number
	 */
	public final void setNumber(Long number)
	{
		setNumber(getContext(), number);
	}

	/**
	 * Set value of Number
	 * @param context
	 * @param number
	 */
	public final void setNumber(com.mendix.systemwideinterfaces.core.IContext context, Long number)
	{
		getMendixObject().setValue(context, MemberNames.Number.toString(), number);
	}

	/**
	 * @return value of RefNr
	 */
	public final Long getRefNr()
	{
		return getRefNr(getContext());
	}

	/**
	 * @param context
	 * @return value of RefNr
	 */
	public final Long getRefNr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Long) getMendixObject().getValue(context, MemberNames.RefNr.toString());
	}

	/**
	 * Set value of RefNr
	 * @param refnr
	 */
	public final void setRefNr(Long refnr)
	{
		setRefNr(getContext(), refnr);
	}

	/**
	 * Set value of RefNr
	 * @param context
	 * @param refnr
	 */
	public final void setRefNr(com.mendix.systemwideinterfaces.core.IContext context, Long refnr)
	{
		getMendixObject().setValue(context, MemberNames.RefNr.toString(), refnr);
	}

	/**
	 * @return value of Description
	 */
	public final String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * Set value of Valid
	 * @param valid
	 */
	public final databasereplication.proxies.YesNo getValid()
	{
		return getValid(getContext());
	}

	/**
	 * @param context
	 * @return value of Valid
	 */
	public final databasereplication.proxies.YesNo getValid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Valid.toString());
		if (obj == null)
			return null;

		return databasereplication.proxies.YesNo.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Valid
	 * @param valid
	 */
	public final void setValid(databasereplication.proxies.YesNo valid)
	{
		setValid(getContext(), valid);
	}

	/**
	 * Set value of Valid
	 * @param context
	 * @param valid
	 */
	public final void setValid(com.mendix.systemwideinterfaces.core.IContext context, databasereplication.proxies.YesNo valid)
	{
		if (valid != null)
			getMendixObject().setValue(context, MemberNames.Valid.toString(), valid.toString());
		else
			getMendixObject().setValue(context, MemberNames.Valid.toString(), null);
	}

	/**
	 * Set value of UseCustomConstraints
	 * @param usecustomconstraints
	 */
	public final databasereplication.proxies.YesNo getUseCustomConstraints()
	{
		return getUseCustomConstraints(getContext());
	}

	/**
	 * @param context
	 * @return value of UseCustomConstraints
	 */
	public final databasereplication.proxies.YesNo getUseCustomConstraints(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.UseCustomConstraints.toString());
		if (obj == null)
			return null;

		return databasereplication.proxies.YesNo.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of UseCustomConstraints
	 * @param usecustomconstraints
	 */
	public final void setUseCustomConstraints(databasereplication.proxies.YesNo usecustomconstraints)
	{
		setUseCustomConstraints(getContext(), usecustomconstraints);
	}

	/**
	 * Set value of UseCustomConstraints
	 * @param context
	 * @param usecustomconstraints
	 */
	public final void setUseCustomConstraints(com.mendix.systemwideinterfaces.core.IContext context, databasereplication.proxies.YesNo usecustomconstraints)
	{
		if (usecustomconstraints != null)
			getMendixObject().setValue(context, MemberNames.UseCustomConstraints.toString(), usecustomconstraints.toString());
		else
			getMendixObject().setValue(context, MemberNames.UseCustomConstraints.toString(), null);
	}

	/**
	 * @return value of SQLConstraint
	 */
	public final String getSQLConstraint()
	{
		return getSQLConstraint(getContext());
	}

	/**
	 * @param context
	 * @return value of SQLConstraint
	 */
	public final String getSQLConstraint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.SQLConstraint.toString());
	}

	/**
	 * Set value of SQLConstraint
	 * @param sqlconstraint
	 */
	public final void setSQLConstraint(String sqlconstraint)
	{
		setSQLConstraint(getContext(), sqlconstraint);
	}

	/**
	 * Set value of SQLConstraint
	 * @param context
	 * @param sqlconstraint
	 */
	public final void setSQLConstraint(com.mendix.systemwideinterfaces.core.IContext context, String sqlconstraint)
	{
		getMendixObject().setValue(context, MemberNames.SQLConstraint.toString(), sqlconstraint);
	}

	/**
	 * Set value of PrintStatisticsMessages
	 * @param printstatisticsmessages
	 */
	public final databasereplication.proxies.StatisticsLevel getPrintStatisticsMessages()
	{
		return getPrintStatisticsMessages(getContext());
	}

	/**
	 * @param context
	 * @return value of PrintStatisticsMessages
	 */
	public final databasereplication.proxies.StatisticsLevel getPrintStatisticsMessages(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.PrintStatisticsMessages.toString());
		if (obj == null)
			return null;

		return databasereplication.proxies.StatisticsLevel.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of PrintStatisticsMessages
	 * @param printstatisticsmessages
	 */
	public final void setPrintStatisticsMessages(databasereplication.proxies.StatisticsLevel printstatisticsmessages)
	{
		setPrintStatisticsMessages(getContext(), printstatisticsmessages);
	}

	/**
	 * Set value of PrintStatisticsMessages
	 * @param context
	 * @param printstatisticsmessages
	 */
	public final void setPrintStatisticsMessages(com.mendix.systemwideinterfaces.core.IContext context, databasereplication.proxies.StatisticsLevel printstatisticsmessages)
	{
		if (printstatisticsmessages != null)
			getMendixObject().setValue(context, MemberNames.PrintStatisticsMessages.toString(), printstatisticsmessages.toString());
		else
			getMendixObject().setValue(context, MemberNames.PrintStatisticsMessages.toString(), null);
	}

	/**
	 * Set value of RemoveUnsyncedObjects
	 * @param removeunsyncedobjects
	 */
	public final databasereplication.proxies.RemoveIndicator getRemoveUnsyncedObjects()
	{
		return getRemoveUnsyncedObjects(getContext());
	}

	/**
	 * @param context
	 * @return value of RemoveUnsyncedObjects
	 */
	public final databasereplication.proxies.RemoveIndicator getRemoveUnsyncedObjects(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.RemoveUnsyncedObjects.toString());
		if (obj == null)
			return null;

		return databasereplication.proxies.RemoveIndicator.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of RemoveUnsyncedObjects
	 * @param removeunsyncedobjects
	 */
	public final void setRemoveUnsyncedObjects(databasereplication.proxies.RemoveIndicator removeunsyncedobjects)
	{
		setRemoveUnsyncedObjects(getContext(), removeunsyncedobjects);
	}

	/**
	 * Set value of RemoveUnsyncedObjects
	 * @param context
	 * @param removeunsyncedobjects
	 */
	public final void setRemoveUnsyncedObjects(com.mendix.systemwideinterfaces.core.IContext context, databasereplication.proxies.RemoveIndicator removeunsyncedobjects)
	{
		if (removeunsyncedobjects != null)
			getMendixObject().setValue(context, MemberNames.RemoveUnsyncedObjects.toString(), removeunsyncedobjects.toString());
		else
			getMendixObject().setValue(context, MemberNames.RemoveUnsyncedObjects.toString(), null);
	}

	/**
	 * Set value of Mode
	 * @param mode
	 */
	public final databasereplication.proxies.Mode getMode()
	{
		return getMode(getContext());
	}

	/**
	 * @param context
	 * @return value of Mode
	 */
	public final databasereplication.proxies.Mode getMode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Mode.toString());
		if (obj == null)
			return null;

		return databasereplication.proxies.Mode.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Mode
	 * @param mode
	 */
	public final void setMode(databasereplication.proxies.Mode mode)
	{
		setMode(getContext(), mode);
	}

	/**
	 * Set value of Mode
	 * @param context
	 * @param mode
	 */
	public final void setMode(com.mendix.systemwideinterfaces.core.IContext context, databasereplication.proxies.Mode mode)
	{
		if (mode != null)
			getMendixObject().setValue(context, MemberNames.Mode.toString(), mode.toString());
		else
			getMendixObject().setValue(context, MemberNames.Mode.toString(), null);
	}

	/**
	 * @return value of UseTransactions
	 */
	public final Boolean getUseTransactions()
	{
		return getUseTransactions(getContext());
	}

	/**
	 * @param context
	 * @return value of UseTransactions
	 */
	public final Boolean getUseTransactions(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.UseTransactions.toString());
	}

	/**
	 * Set value of UseTransactions
	 * @param usetransactions
	 */
	public final void setUseTransactions(Boolean usetransactions)
	{
		setUseTransactions(getContext(), usetransactions);
	}

	/**
	 * Set value of UseTransactions
	 * @param context
	 * @param usetransactions
	 */
	public final void setUseTransactions(com.mendix.systemwideinterfaces.core.IContext context, Boolean usetransactions)
	{
		getMendixObject().setValue(context, MemberNames.UseTransactions.toString(), usetransactions);
	}

	/**
	 * @return value of ImportInNewContext
	 */
	public final Boolean getImportInNewContext()
	{
		return getImportInNewContext(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportInNewContext
	 */
	public final Boolean getImportInNewContext(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.ImportInNewContext.toString());
	}

	/**
	 * Set value of ImportInNewContext
	 * @param importinnewcontext
	 */
	public final void setImportInNewContext(Boolean importinnewcontext)
	{
		setImportInNewContext(getContext(), importinnewcontext);
	}

	/**
	 * Set value of ImportInNewContext
	 * @param context
	 * @param importinnewcontext
	 */
	public final void setImportInNewContext(com.mendix.systemwideinterfaces.core.IContext context, Boolean importinnewcontext)
	{
		getMendixObject().setValue(context, MemberNames.ImportInNewContext.toString(), importinnewcontext);
	}

	/**
	 * @return value of IgnoreEmptyKeys
	 */
	public final Boolean getIgnoreEmptyKeys()
	{
		return getIgnoreEmptyKeys(getContext());
	}

	/**
	 * @param context
	 * @return value of IgnoreEmptyKeys
	 */
	public final Boolean getIgnoreEmptyKeys(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.IgnoreEmptyKeys.toString());
	}

	/**
	 * Set value of IgnoreEmptyKeys
	 * @param ignoreemptykeys
	 */
	public final void setIgnoreEmptyKeys(Boolean ignoreemptykeys)
	{
		setIgnoreEmptyKeys(getContext(), ignoreemptykeys);
	}

	/**
	 * Set value of IgnoreEmptyKeys
	 * @param context
	 * @param ignoreemptykeys
	 */
	public final void setIgnoreEmptyKeys(com.mendix.systemwideinterfaces.core.IContext context, Boolean ignoreemptykeys)
	{
		getMendixObject().setValue(context, MemberNames.IgnoreEmptyKeys.toString(), ignoreemptykeys);
	}

	/**
	 * Set value of ImportAction
	 * @param importaction
	 */
	public final databasereplication.proxies.ImportAction getImportAction()
	{
		return getImportAction(getContext());
	}

	/**
	 * @param context
	 * @return value of ImportAction
	 */
	public final databasereplication.proxies.ImportAction getImportAction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ImportAction.toString());
		if (obj == null)
			return null;

		return databasereplication.proxies.ImportAction.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ImportAction
	 * @param importaction
	 */
	public final void setImportAction(databasereplication.proxies.ImportAction importaction)
	{
		setImportAction(getContext(), importaction);
	}

	/**
	 * Set value of ImportAction
	 * @param context
	 * @param importaction
	 */
	public final void setImportAction(com.mendix.systemwideinterfaces.core.IContext context, databasereplication.proxies.ImportAction importaction)
	{
		if (importaction != null)
			getMendixObject().setValue(context, MemberNames.ImportAction.toString(), importaction.toString());
		else
			getMendixObject().setValue(context, MemberNames.ImportAction.toString(), null);
	}

	/**
	 * @return value of ResetEmptyAssociations
	 */
	public final Boolean getResetEmptyAssociations()
	{
		return getResetEmptyAssociations(getContext());
	}

	/**
	 * @param context
	 * @return value of ResetEmptyAssociations
	 */
	public final Boolean getResetEmptyAssociations(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.ResetEmptyAssociations.toString());
	}

	/**
	 * Set value of ResetEmptyAssociations
	 * @param resetemptyassociations
	 */
	public final void setResetEmptyAssociations(Boolean resetemptyassociations)
	{
		setResetEmptyAssociations(getContext(), resetemptyassociations);
	}

	/**
	 * Set value of ResetEmptyAssociations
	 * @param context
	 * @param resetemptyassociations
	 */
	public final void setResetEmptyAssociations(com.mendix.systemwideinterfaces.core.IContext context, Boolean resetemptyassociations)
	{
		getMendixObject().setValue(context, MemberNames.ResetEmptyAssociations.toString(), resetemptyassociations);
	}

	/**
	 * @return value of CommitUnchangedObjects_MainObject
	 */
	public final Boolean getCommitUnchangedObjects_MainObject()
	{
		return getCommitUnchangedObjects_MainObject(getContext());
	}

	/**
	 * @param context
	 * @return value of CommitUnchangedObjects_MainObject
	 */
	public final Boolean getCommitUnchangedObjects_MainObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.CommitUnchangedObjects_MainObject.toString());
	}

	/**
	 * Set value of CommitUnchangedObjects_MainObject
	 * @param commitunchangedobjects_mainobject
	 */
	public final void setCommitUnchangedObjects_MainObject(Boolean commitunchangedobjects_mainobject)
	{
		setCommitUnchangedObjects_MainObject(getContext(), commitunchangedobjects_mainobject);
	}

	/**
	 * Set value of CommitUnchangedObjects_MainObject
	 * @param context
	 * @param commitunchangedobjects_mainobject
	 */
	public final void setCommitUnchangedObjects_MainObject(com.mendix.systemwideinterfaces.core.IContext context, Boolean commitunchangedobjects_mainobject)
	{
		getMendixObject().setValue(context, MemberNames.CommitUnchangedObjects_MainObject.toString(), commitunchangedobjects_mainobject);
	}

	/**
	 * @return value of PrintNotFoundMessages_MainObject
	 */
	public final Boolean getPrintNotFoundMessages_MainObject()
	{
		return getPrintNotFoundMessages_MainObject(getContext());
	}

	/**
	 * @param context
	 * @return value of PrintNotFoundMessages_MainObject
	 */
	public final Boolean getPrintNotFoundMessages_MainObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.PrintNotFoundMessages_MainObject.toString());
	}

	/**
	 * Set value of PrintNotFoundMessages_MainObject
	 * @param printnotfoundmessages_mainobject
	 */
	public final void setPrintNotFoundMessages_MainObject(Boolean printnotfoundmessages_mainobject)
	{
		setPrintNotFoundMessages_MainObject(getContext(), printnotfoundmessages_mainobject);
	}

	/**
	 * Set value of PrintNotFoundMessages_MainObject
	 * @param context
	 * @param printnotfoundmessages_mainobject
	 */
	public final void setPrintNotFoundMessages_MainObject(com.mendix.systemwideinterfaces.core.IContext context, Boolean printnotfoundmessages_mainobject)
	{
		getMendixObject().setValue(context, MemberNames.PrintNotFoundMessages_MainObject.toString(), printnotfoundmessages_mainobject);
	}

	/**
	 * Set value of DatabaseType
	 * @param databasetype
	 */
	public final databasereplication.proxies.DBType getDatabaseType()
	{
		return getDatabaseType(getContext());
	}

	/**
	 * @param context
	 * @return value of DatabaseType
	 */
	public final databasereplication.proxies.DBType getDatabaseType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.DatabaseType.toString());
		if (obj == null)
			return null;

		return databasereplication.proxies.DBType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of DatabaseType
	 * @param databasetype
	 */
	public final void setDatabaseType(databasereplication.proxies.DBType databasetype)
	{
		setDatabaseType(getContext(), databasetype);
	}

	/**
	 * Set value of DatabaseType
	 * @param context
	 * @param databasetype
	 */
	public final void setDatabaseType(com.mendix.systemwideinterfaces.core.IContext context, databasereplication.proxies.DBType databasetype)
	{
		if (databasetype != null)
			getMendixObject().setValue(context, MemberNames.DatabaseType.toString(), databasetype.toString());
		else
			getMendixObject().setValue(context, MemberNames.DatabaseType.toString(), null);
	}

	/**
	 * @return value of TableMapping_Table
	 */
	public final databasereplication.proxies.Table getTableMapping_Table() throws com.mendix.core.CoreException
	{
		return getTableMapping_Table(getContext());
	}

	/**
	 * @param context
	 * @return value of TableMapping_Table
	 */
	public final databasereplication.proxies.Table getTableMapping_Table(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		databasereplication.proxies.Table result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TableMapping_Table.toString());
		if (identifier != null)
			result = databasereplication.proxies.Table.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TableMapping_Table
	 * @param tablemapping_table
	 */
	public final void setTableMapping_Table(databasereplication.proxies.Table tablemapping_table)
	{
		setTableMapping_Table(getContext(), tablemapping_table);
	}

	/**
	 * Set value of TableMapping_Table
	 * @param context
	 * @param tablemapping_table
	 */
	public final void setTableMapping_Table(com.mendix.systemwideinterfaces.core.IContext context, databasereplication.proxies.Table tablemapping_table)
	{
		if (tablemapping_table == null)
			getMendixObject().setValue(context, MemberNames.TableMapping_Table.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TableMapping_Table.toString(), tablemapping_table.getMendixObject().getId());
	}

	/**
	 * @return value of TableMapping_Database
	 */
	public final databasereplication.proxies.Database getTableMapping_Database() throws com.mendix.core.CoreException
	{
		return getTableMapping_Database(getContext());
	}

	/**
	 * @param context
	 * @return value of TableMapping_Database
	 */
	public final databasereplication.proxies.Database getTableMapping_Database(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		databasereplication.proxies.Database result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TableMapping_Database.toString());
		if (identifier != null)
			result = databasereplication.proxies.Database.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TableMapping_Database
	 * @param tablemapping_database
	 */
	public final void setTableMapping_Database(databasereplication.proxies.Database tablemapping_database)
	{
		setTableMapping_Database(getContext(), tablemapping_database);
	}

	/**
	 * Set value of TableMapping_Database
	 * @param context
	 * @param tablemapping_database
	 */
	public final void setTableMapping_Database(com.mendix.systemwideinterfaces.core.IContext context, databasereplication.proxies.Database tablemapping_database)
	{
		if (tablemapping_database == null)
			getMendixObject().setValue(context, MemberNames.TableMapping_Database.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TableMapping_Database.toString(), tablemapping_database.getMendixObject().getId());
	}

	/**
	 * @return value of TableMapping_XMLDocumentTM
	 */
	public final databasereplication.proxies.XMLDocumentTM getTableMapping_XMLDocumentTM() throws com.mendix.core.CoreException
	{
		return getTableMapping_XMLDocumentTM(getContext());
	}

	/**
	 * @param context
	 * @return value of TableMapping_XMLDocumentTM
	 */
	public final databasereplication.proxies.XMLDocumentTM getTableMapping_XMLDocumentTM(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		databasereplication.proxies.XMLDocumentTM result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TableMapping_XMLDocumentTM.toString());
		if (identifier != null)
			result = databasereplication.proxies.XMLDocumentTM.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TableMapping_XMLDocumentTM
	 * @param tablemapping_xmldocumenttm
	 */
	public final void setTableMapping_XMLDocumentTM(databasereplication.proxies.XMLDocumentTM tablemapping_xmldocumenttm)
	{
		setTableMapping_XMLDocumentTM(getContext(), tablemapping_xmldocumenttm);
	}

	/**
	 * Set value of TableMapping_XMLDocumentTM
	 * @param context
	 * @param tablemapping_xmldocumenttm
	 */
	public final void setTableMapping_XMLDocumentTM(com.mendix.systemwideinterfaces.core.IContext context, databasereplication.proxies.XMLDocumentTM tablemapping_xmldocumenttm)
	{
		if (tablemapping_xmldocumenttm == null)
			getMendixObject().setValue(context, MemberNames.TableMapping_XMLDocumentTM.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TableMapping_XMLDocumentTM.toString(), tablemapping_xmldocumenttm.getMendixObject().getId());
	}

	/**
	 * @return value of TableMapping_MxObjectType
	 */
	public final mxmodelreflection.proxies.MxObjectType getTableMapping_MxObjectType() throws com.mendix.core.CoreException
	{
		return getTableMapping_MxObjectType(getContext());
	}

	/**
	 * @param context
	 * @return value of TableMapping_MxObjectType
	 */
	public final mxmodelreflection.proxies.MxObjectType getTableMapping_MxObjectType(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxmodelreflection.proxies.MxObjectType result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TableMapping_MxObjectType.toString());
		if (identifier != null)
			result = mxmodelreflection.proxies.MxObjectType.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TableMapping_MxObjectType
	 * @param tablemapping_mxobjecttype
	 */
	public final void setTableMapping_MxObjectType(mxmodelreflection.proxies.MxObjectType tablemapping_mxobjecttype)
	{
		setTableMapping_MxObjectType(getContext(), tablemapping_mxobjecttype);
	}

	/**
	 * Set value of TableMapping_MxObjectType
	 * @param context
	 * @param tablemapping_mxobjecttype
	 */
	public final void setTableMapping_MxObjectType(com.mendix.systemwideinterfaces.core.IContext context, mxmodelreflection.proxies.MxObjectType tablemapping_mxobjecttype)
	{
		if (tablemapping_mxobjecttype == null)
			getMendixObject().setValue(context, MemberNames.TableMapping_MxObjectType.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TableMapping_MxObjectType.toString(), tablemapping_mxobjecttype.getMendixObject().getId());
	}

	/**
	 * @return value of TableMapping_MxObjectMember
	 */
	public final mxmodelreflection.proxies.MxObjectMember getTableMapping_MxObjectMember() throws com.mendix.core.CoreException
	{
		return getTableMapping_MxObjectMember(getContext());
	}

	/**
	 * @param context
	 * @return value of TableMapping_MxObjectMember
	 */
	public final mxmodelreflection.proxies.MxObjectMember getTableMapping_MxObjectMember(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxmodelreflection.proxies.MxObjectMember result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TableMapping_MxObjectMember.toString());
		if (identifier != null)
			result = mxmodelreflection.proxies.MxObjectMember.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TableMapping_MxObjectMember
	 * @param tablemapping_mxobjectmember
	 */
	public final void setTableMapping_MxObjectMember(mxmodelreflection.proxies.MxObjectMember tablemapping_mxobjectmember)
	{
		setTableMapping_MxObjectMember(getContext(), tablemapping_mxobjectmember);
	}

	/**
	 * Set value of TableMapping_MxObjectMember
	 * @param context
	 * @param tablemapping_mxobjectmember
	 */
	public final void setTableMapping_MxObjectMember(com.mendix.systemwideinterfaces.core.IContext context, mxmodelreflection.proxies.MxObjectMember tablemapping_mxobjectmember)
	{
		if (tablemapping_mxobjectmember == null)
			getMendixObject().setValue(context, MemberNames.TableMapping_MxObjectMember.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TableMapping_MxObjectMember.toString(), tablemapping_mxobjectmember.getMendixObject().getId());
	}

	/**
	 * @return value of TableMapping_Microflows
	 */
	public final mxmodelreflection.proxies.Microflows getTableMapping_Microflows() throws com.mendix.core.CoreException
	{
		return getTableMapping_Microflows(getContext());
	}

	/**
	 * @param context
	 * @return value of TableMapping_Microflows
	 */
	public final mxmodelreflection.proxies.Microflows getTableMapping_Microflows(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mxmodelreflection.proxies.Microflows result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TableMapping_Microflows.toString());
		if (identifier != null)
			result = mxmodelreflection.proxies.Microflows.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TableMapping_Microflows
	 * @param tablemapping_microflows
	 */
	public final void setTableMapping_Microflows(mxmodelreflection.proxies.Microflows tablemapping_microflows)
	{
		setTableMapping_Microflows(getContext(), tablemapping_microflows);
	}

	/**
	 * Set value of TableMapping_Microflows
	 * @param context
	 * @param tablemapping_microflows
	 */
	public final void setTableMapping_Microflows(com.mendix.systemwideinterfaces.core.IContext context, mxmodelreflection.proxies.Microflows tablemapping_microflows)
	{
		if (tablemapping_microflows == null)
			getMendixObject().setValue(context, MemberNames.TableMapping_Microflows.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TableMapping_Microflows.toString(), tablemapping_microflows.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return tableMappingMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final databasereplication.proxies.TableMapping that = (databasereplication.proxies.TableMapping) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DatabaseReplication.TableMapping";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
