// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databasereplication.proxies;

public enum UpdateType
{
	AlwaysInsert(new String[][] { new String[] { "en_US", "Always Insert" }, new String[] { "nl_NL", "Altijd een INSERT" }, new String[] { "en_GB", "Always Insert" }, new String[] { "en_ZA", "Always Insert" } }),
	UpdateOnly(new String[][] { new String[] { "en_US", "Update Only" }, new String[] { "nl_NL", "Alleen Update" }, new String[] { "en_GB", "Update Only" }, new String[] { "en_ZA", "Update Only" } }),
	UpdateOrInsert(new String[][] { new String[] { "en_US", "Update Or Insert" }, new String[] { "nl_NL", "Update of Insert" }, new String[] { "en_GB", "Update Or Insert" }, new String[] { "en_ZA", "Update Or Insert" } });

	private java.util.Map<String,String> captions;

	private UpdateType(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
