// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databasereplication.proxies;

public enum Validation_ColumnMapping
{
	Valid(new String[][] { new String[] { "en_US", "Valid" }, new String[] { "nl_NL", "Geldig" }, new String[] { "en_GB", "Valid" }, new String[] { "en_ZA", "Valid" } }),
	NoTableSelected(new String[][] { new String[] { "en_US", "NoTableSelected" }, new String[] { "nl_NL", "NoTableSelected" }, new String[] { "en_GB", "NoTableSelected" }, new String[] { "en_ZA", "NoTableSelected" } }),
	NoAttributeSelected(new String[][] { new String[] { "en_US", "NoAttributeSelected" }, new String[] { "nl_NL", "NoAttributeSelected" }, new String[] { "en_GB", "NoAttributeSelected" }, new String[] { "en_ZA", "NoAttributeSelected" } }),
	NoMicroflowSelected(new String[][] { new String[] { "en_US", "NoMicroflowSelected" }, new String[] { "nl_NL", "NoMicroflowSelected" }, new String[] { "en_GB", "NoMicroflowSelected" }, new String[] { "en_ZA", "NoMicroflowSelected" } }),
	NoColumnSelected(new String[][] { new String[] { "en_US", "NoColumnSelected" }, new String[] { "nl_NL", "NoColumnSelected" }, new String[] { "en_GB", "NoColumnSelected" }, new String[] { "en_ZA", "NoColumnSelected" } }),
	NoCustomSelectStatement(new String[][] { new String[] { "en_US", "NoCustomSelectStatement" }, new String[] { "nl_NL", "NoCustomSelectStatement" }, new String[] { "en_GB", "NoCustomSelectStatement" }, new String[] { "en_ZA", "NoCustomSelectStatement" } }),
	NoReferenceSelected(new String[][] { new String[] { "en_US", "NoReferenceSelected" }, new String[] { "nl_NL", "NoReferenceSelected" }, new String[] { "en_GB", "NoReferenceSelected" }, new String[] { "en_ZA", "NoReferenceSelected" } }),
	NoObjectTypeSelected(new String[][] { new String[] { "en_US", "NoObjectTypeSelected" }, new String[] { "nl_NL", "NoObjectTypeSelected" }, new String[] { "en_GB", "NoObjectTypeSelected" }, new String[] { "en_ZA", "NoObjectTypeSelected" } });

	private java.util.Map<String,String> captions;

	private Validation_ColumnMapping(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
