// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databasereplication.proxies;

public class XMLDocumentTM extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DatabaseReplication.XMLDocumentTM";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Database_XMLDocumentTM("DatabaseReplication.Database_XMLDocumentTM");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public XMLDocumentTM(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DatabaseReplication.XMLDocumentTM"));
	}

	protected XMLDocumentTM(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject xMLDocumentTMMendixObject)
	{
		super(context, xMLDocumentTMMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("DatabaseReplication.XMLDocumentTM", xMLDocumentTMMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DatabaseReplication.XMLDocumentTM");
	}

	/**
	 * @deprecated Use 'XMLDocumentTM.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static databasereplication.proxies.XMLDocumentTM initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return databasereplication.proxies.XMLDocumentTM.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static databasereplication.proxies.XMLDocumentTM initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new databasereplication.proxies.XMLDocumentTM(context, mendixObject);
	}

	public static databasereplication.proxies.XMLDocumentTM load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return databasereplication.proxies.XMLDocumentTM.initialize(context, mendixObject);
	}

	public static java.util.List<databasereplication.proxies.XMLDocumentTM> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<databasereplication.proxies.XMLDocumentTM> result = new java.util.ArrayList<databasereplication.proxies.XMLDocumentTM>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DatabaseReplication.XMLDocumentTM" + xpathConstraint))
			result.add(databasereplication.proxies.XMLDocumentTM.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of Database_XMLDocumentTM
	 */
	public final databasereplication.proxies.Database getDatabase_XMLDocumentTM() throws com.mendix.core.CoreException
	{
		return getDatabase_XMLDocumentTM(getContext());
	}

	/**
	 * @param context
	 * @return value of Database_XMLDocumentTM
	 */
	public final databasereplication.proxies.Database getDatabase_XMLDocumentTM(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		databasereplication.proxies.Database result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Database_XMLDocumentTM.toString());
		if (identifier != null)
			result = databasereplication.proxies.Database.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Database_XMLDocumentTM
	 * @param database_xmldocumenttm
	 */
	public final void setDatabase_XMLDocumentTM(databasereplication.proxies.Database database_xmldocumenttm)
	{
		setDatabase_XMLDocumentTM(getContext(), database_xmldocumenttm);
	}

	/**
	 * Set value of Database_XMLDocumentTM
	 * @param context
	 * @param database_xmldocumenttm
	 */
	public final void setDatabase_XMLDocumentTM(com.mendix.systemwideinterfaces.core.IContext context, databasereplication.proxies.Database database_xmldocumenttm)
	{
		if (database_xmldocumenttm == null)
			getMendixObject().setValue(context, MemberNames.Database_XMLDocumentTM.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Database_XMLDocumentTM.toString(), database_xmldocumenttm.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final databasereplication.proxies.XMLDocumentTM that = (databasereplication.proxies.XMLDocumentTM) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DatabaseReplication.XMLDocumentTM";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
