// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emailtemplate.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class EmailSettings
{
	private final IMendixObject emailSettingsMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "EmailTemplate.EmailSettings";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		UserName("UserName"),
		Password("Password"),
		Server("Server"),
		Port("Port"),
		FromAddress("FromAddress"),
		UseSSL("UseSSL"),
		UseTLS("UseTLS"),
		MaxAttempts("MaxAttempts");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public EmailSettings(IContext context)
	{
		this(context, Core.instantiate(context, "EmailTemplate.EmailSettings"));
	}

	protected EmailSettings(IContext context, IMendixObject emailSettingsMendixObject)
	{
		if (emailSettingsMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("EmailTemplate.EmailSettings", emailSettingsMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a EmailTemplate.EmailSettings");

		this.emailSettingsMendixObject = emailSettingsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'EmailSettings.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static emailtemplate.proxies.EmailSettings initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return emailtemplate.proxies.EmailSettings.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static emailtemplate.proxies.EmailSettings initialize(IContext context, IMendixObject mendixObject)
	{
		return new emailtemplate.proxies.EmailSettings(context, mendixObject);
	}

	public static emailtemplate.proxies.EmailSettings load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return emailtemplate.proxies.EmailSettings.initialize(context, mendixObject);
	}

	public static java.util.List<emailtemplate.proxies.EmailSettings> load(IContext context, String xpathConstraint) throws CoreException
	{
		java.util.List<emailtemplate.proxies.EmailSettings> result = new java.util.ArrayList<emailtemplate.proxies.EmailSettings>();
		for (IMendixObject obj : Core.retrieveXPathQuery(context, "//EmailTemplate.EmailSettings" + xpathConstraint))
			result.add(emailtemplate.proxies.EmailSettings.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of UserName
	 */
	public final String getUserName()
	{
		return getUserName(getContext());
	}

	/**
	 * @param context
	 * @return value of UserName
	 */
	public final String getUserName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.UserName.toString());
	}

	/**
	 * Set value of UserName
	 * @param username
	 */
	public final void setUserName(String username)
	{
		setUserName(getContext(), username);
	}

	/**
	 * Set value of UserName
	 * @param context
	 * @param username
	 */
	public final void setUserName(IContext context, String username)
	{
		getMendixObject().setValue(context, MemberNames.UserName.toString(), username);
	}

	/**
	 * @return value of Password
	 */
	public final String getPassword()
	{
		return getPassword(getContext());
	}

	/**
	 * @param context
	 * @return value of Password
	 */
	public final String getPassword(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Password.toString());
	}

	/**
	 * Set value of Password
	 * @param password
	 */
	public final void setPassword(String password)
	{
		setPassword(getContext(), password);
	}

	/**
	 * Set value of Password
	 * @param context
	 * @param password
	 */
	public final void setPassword(IContext context, String password)
	{
		getMendixObject().setValue(context, MemberNames.Password.toString(), password);
	}

	/**
	 * @return value of Server
	 */
	public final String getServer()
	{
		return getServer(getContext());
	}

	/**
	 * @param context
	 * @return value of Server
	 */
	public final String getServer(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Server.toString());
	}

	/**
	 * Set value of Server
	 * @param server
	 */
	public final void setServer(String server)
	{
		setServer(getContext(), server);
	}

	/**
	 * Set value of Server
	 * @param context
	 * @param server
	 */
	public final void setServer(IContext context, String server)
	{
		getMendixObject().setValue(context, MemberNames.Server.toString(), server);
	}

	/**
	 * @return value of Port
	 */
	public final Integer getPort()
	{
		return getPort(getContext());
	}

	/**
	 * @param context
	 * @return value of Port
	 */
	public final Integer getPort(IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.Port.toString());
	}

	/**
	 * Set value of Port
	 * @param port
	 */
	public final void setPort(Integer port)
	{
		setPort(getContext(), port);
	}

	/**
	 * Set value of Port
	 * @param context
	 * @param port
	 */
	public final void setPort(IContext context, Integer port)
	{
		getMendixObject().setValue(context, MemberNames.Port.toString(), port);
	}

	/**
	 * @return value of FromAddress
	 */
	public final String getFromAddress()
	{
		return getFromAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of FromAddress
	 */
	public final String getFromAddress(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.FromAddress.toString());
	}

	/**
	 * Set value of FromAddress
	 * @param fromaddress
	 */
	public final void setFromAddress(String fromaddress)
	{
		setFromAddress(getContext(), fromaddress);
	}

	/**
	 * Set value of FromAddress
	 * @param context
	 * @param fromaddress
	 */
	public final void setFromAddress(IContext context, String fromaddress)
	{
		getMendixObject().setValue(context, MemberNames.FromAddress.toString(), fromaddress);
	}

	/**
	 * @return value of UseSSL
	 */
	public final Boolean getUseSSL()
	{
		return getUseSSL(getContext());
	}

	/**
	 * @param context
	 * @return value of UseSSL
	 */
	public final Boolean getUseSSL(IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.UseSSL.toString());
	}

	/**
	 * Set value of UseSSL
	 * @param usessl
	 */
	public final void setUseSSL(Boolean usessl)
	{
		setUseSSL(getContext(), usessl);
	}

	/**
	 * Set value of UseSSL
	 * @param context
	 * @param usessl
	 */
	public final void setUseSSL(IContext context, Boolean usessl)
	{
		getMendixObject().setValue(context, MemberNames.UseSSL.toString(), usessl);
	}

	/**
	 * @return value of UseTLS
	 */
	public final Boolean getUseTLS()
	{
		return getUseTLS(getContext());
	}

	/**
	 * @param context
	 * @return value of UseTLS
	 */
	public final Boolean getUseTLS(IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.UseTLS.toString());
	}

	/**
	 * Set value of UseTLS
	 * @param usetls
	 */
	public final void setUseTLS(Boolean usetls)
	{
		setUseTLS(getContext(), usetls);
	}

	/**
	 * Set value of UseTLS
	 * @param context
	 * @param usetls
	 */
	public final void setUseTLS(IContext context, Boolean usetls)
	{
		getMendixObject().setValue(context, MemberNames.UseTLS.toString(), usetls);
	}

	/**
	 * @return value of MaxAttempts
	 */
	public final Integer getMaxAttempts()
	{
		return getMaxAttempts(getContext());
	}

	/**
	 * @param context
	 * @return value of MaxAttempts
	 */
	public final Integer getMaxAttempts(IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.MaxAttempts.toString());
	}

	/**
	 * Set value of MaxAttempts
	 * @param maxattempts
	 */
	public final void setMaxAttempts(Integer maxattempts)
	{
		setMaxAttempts(getContext(), maxattempts);
	}

	/**
	 * Set value of MaxAttempts
	 * @param context
	 * @param maxattempts
	 */
	public final void setMaxAttempts(IContext context, Integer maxattempts)
	{
		getMendixObject().setValue(context, MemberNames.MaxAttempts.toString(), maxattempts);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return emailSettingsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final emailtemplate.proxies.EmailSettings that = (emailtemplate.proxies.EmailSettings) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "EmailTemplate.EmailSettings";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
