// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emailtemplate.proxies;

public enum LogType
{
	Message(new String[][] { new String[] { "en_US", "Message" }, new String[] { "en_GB", "Message" }, new String[] { "en_ZA", "Message" }, new String[] { "nl_NL", "Bericht" } }),
	Warning(new String[][] { new String[] { "en_US", "Warning" }, new String[] { "en_GB", "Warning" }, new String[] { "en_ZA", "Warning" }, new String[] { "nl_NL", "Waarschuwing" } }),
	Error(new String[][] { new String[] { "en_US", "Error" }, new String[] { "en_GB", "Error" }, new String[] { "en_ZA", "Error" }, new String[] { "nl_NL", "Fout" } });

	private java.util.Map<String,String> captions;

	private LogType(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
