// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emailtemplate.proxies;

public enum Status
{
	QUEUED(new String[][] { new String[] { "en_US", "Queued" }, new String[] { "en_GB", "Queued" }, new String[] { "en_ZA", "Queued" }, new String[] { "nl_NL", "In wachtrij" } }),
	SENT(new String[][] { new String[] { "en_US", "Sent" }, new String[] { "en_GB", "Sent" }, new String[] { "en_ZA", "Sent" }, new String[] { "nl_NL", "Verzonden" } }),
	FAILED(new String[][] { new String[] { "en_US", "Failed" }, new String[] { "en_GB", "Failed" }, new String[] { "en_ZA", "Failed" }, new String[] { "nl_NL", "Gefaald" } }),
	ERROR(new String[][] { new String[] { "en_US", "Error" }, new String[] { "en_GB", "Error" }, new String[] { "en_ZA", "Error" }, new String[] { "nl_NL", "Fout" } });

	private java.util.Map<String,String> captions;

	private Status(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
