// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emailtemplate.proxies;

public enum Status
{
	QUEUED(new java.lang.String[][] { new java.lang.String[] { "en_US", "Queued" }, new java.lang.String[] { "en_GB", "Queued" }, new java.lang.String[] { "en_ZA", "Queued" }, new java.lang.String[] { "nl_NL", "In wachtrij" } }),
	SENT(new java.lang.String[][] { new java.lang.String[] { "en_US", "Sent" }, new java.lang.String[] { "en_GB", "Sent" }, new java.lang.String[] { "en_ZA", "Sent" }, new java.lang.String[] { "nl_NL", "Verzonden" } }),
	FAILED(new java.lang.String[][] { new java.lang.String[] { "en_US", "Failed" }, new java.lang.String[] { "en_GB", "Failed" }, new java.lang.String[] { "en_ZA", "Failed" }, new java.lang.String[] { "nl_NL", "Gefaald" } }),
	ERROR(new java.lang.String[][] { new java.lang.String[] { "en_US", "Error" }, new java.lang.String[] { "en_GB", "Error" }, new java.lang.String[] { "en_ZA", "Error" }, new java.lang.String[] { "nl_NL", "Fout" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private Status(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
