// This file was generated by Mendix Business Modeler 5.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package encryption.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the Encryption module

	public static String decrypt(IContext context, String _encrypted)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Encrypted", _encrypted);
			return (String)Core.execute(context, "Encryption.Decrypt", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static String encrypt(IContext context, String _plain)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Plain", _plain);
			return (String)Core.execute(context, "Encryption.Encrypt", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_ChangePassword(IContext context, encryption.proxies.ExampleConfiguration _exampleConfiguration)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("ExampleConfiguration", _exampleConfiguration == null ? null : _exampleConfiguration.getMendixObject());
			Core.execute(context, "Encryption.IVK_ChangePassword", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_ChangePasswordSave(IContext context, encryption.proxies.PasswordData _passwordData)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("PasswordData", _passwordData == null ? null : _passwordData.getMendixObject());
			Core.execute(context, "Encryption.IVK_ChangePasswordSave", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}