// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package googlecharts.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import java.math.BigDecimal;

public class Sin extends CustomJavaAction<java.math.BigDecimal>
{
	private java.math.BigDecimal Parameter;

	public Sin(IContext context, java.math.BigDecimal Parameter)
	{
		super(context);
		this.Parameter = Parameter;
	}

	@Override
	public java.math.BigDecimal executeAction() throws Exception
	{
		// BEGIN USER CODE
		return BigDecimal.valueOf(Math.sin(Parameter.doubleValue()));

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "Sin";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
